#!/usr/bin/env python3
"""Add musical key + main chords to SeedCatalog.json songs.

Hand-authored for the most iconic songs (same editorial approach as the gold
tones). Matching is transliteration-normalized "title|artist". Idempotent.
Run: python3 tools/add_song_keys.py [path-to-SeedCatalog.json]
"""
import json
import sys
import unicodedata

# "Title|Artist": ("Key", "Main chords")
K = {
    # ---- International classics ----
    "Comfortably Numb|Pink Floyd": ("B minor", "Bm – A – G – Em"),
    "Another Brick in the Wall, Pt. 2|Pink Floyd": ("D minor", "Dm – G – F – C"),
    "Wish You Were Here|Pink Floyd": ("G major", "Em7 – G – A7sus4 – C – D"),
    "Time|Pink Floyd": ("F# minor", "F#m – A – E – F#m"),
    "Money|Pink Floyd": ("B minor", "Bm7 – F#m – Em"),
    "Shine On You Crazy Diamond|Pink Floyd": ("G minor", "Gm – Cm – D"),
    "Purple Haze|Jimi Hendrix": ("E (E7#9)", "E7#9 – G – A"),
    "Little Wing|Jimi Hendrix": ("E minor", "Em – G – Am – Bm – B♭ – C – D"),
    "Voodoo Child (Slight Return)|Jimi Hendrix": ("E minor", "E7#9 riff – wah groove"),
    "All Along the Watchtower|Jimi Hendrix": ("C# minor", "C#m – B – A – B"),
    "Hey Joe|Jimi Hendrix": ("E major", "C – G – D – A – E"),
    "Enter Sandman|Metallica": ("E minor", "Em – A♭dim riff"),
    "Master of Puppets|Metallica": ("E minor", "E5 chromatic riff"),
    "Nothing Else Matters|Metallica": ("E minor", "Em – Am – C – D"),
    "One|Metallica": ("B minor", "Bm – G – A intro"),
    "Fade to Black|Metallica": ("B minor", "Bm – A – G – Em arpeggios"),
    "Sad But True|Metallica": ("E minor (D tuning)", "E5 – G5 drop riff"),
    "The Unforgiven|Metallica": ("A minor", "Am – C – G – Em"),
    "Sweet Child O' Mine|Guns N' Roses": ("D major", "D – C – G intro riff"),
    "Welcome to the Jungle|Guns N' Roses": ("A minor", "A5 riff – Cadd9"),
    "November Rain|Guns N' Roses": ("C major", "C – F – G – Am"),
    "Paradise City|Guns N' Roses": ("G major", "G – C – F – C – G"),
    "Knockin' On Heaven's Door|Guns N' Roses": ("G major", "G – D – Am7 – C"),
    "Stairway to Heaven|Led Zeppelin": ("A minor", "Am – E+ – C – D – F"),
    "Whole Lotta Love|Led Zeppelin": ("E major", "E5 – D5 riff"),
    "Kashmir|Led Zeppelin": ("D (DADGAD)", "D – Dsus4 ascending riff"),
    "Black Dog|Led Zeppelin": ("A major", "A blues riff"),
    "Rock and Roll|Led Zeppelin": ("A major", "A – D – E 12-bar"),
    "Immigrant Song|Led Zeppelin": ("F# minor", "F#5 gallop riff"),
    "Since I've Been Loving You|Led Zeppelin": ("C minor", "Cm slow blues"),
    "Smoke On the Water|Deep Purple": ("G minor", "G5 – B♭5 – C5 riff"),
    "Highway Star|Deep Purple": ("G minor", "G5 driving riff"),
    "Child In Time|Deep Purple": ("A minor", "Am – G – F"),
    "Burn|Deep Purple": ("G minor", "G5 riff – E♭ – F"),
    "Back In Black|AC/DC": ("E major", "E – D – A riff"),
    "Highway to Hell|AC/DC": ("A major", "A – D/F# – G riff"),
    "Thunderstruck|AC/DC": ("B minor", "B pull-off riff – A – E"),
    "You Shook Me All Night Long|AC/DC": ("G major", "G – C – D"),
    "Hells Bells|AC/DC": ("A minor", "Am – C – G arpeggio riff"),
    "Bohemian Rhapsody|Queen": ("B♭ major", "B♭ – Gm – Cm – F"),
    "We Will Rock You|Queen": ("C major", "C5 stomp – A – D solo"),
    "Don't Stop Me Now|Queen": ("F major", "F – Am – Dm – Gm – C"),
    "Smells Like Teen Spirit|Nirvana": ("F minor", "F5 – B♭5 – A♭5 – D♭5"),
    "Come As You Are|Nirvana": ("E minor (D tuning)", "Em – D riff"),
    "Heart-Shaped Box|Nirvana": ("A minor (drop D)", "A5 – F5 – D♭5"),
    "Lithium|Nirvana": ("D major", "D5 – F#5 – B5 – G5 – B♭5 – C5 – A5 – C5"),
    "In Bloom|Nirvana": ("B♭ major", "B♭5 – G♭5 riff"),
    "Black|Pearl Jam": ("E major", "E – Asus2"),
    "Alive|Pearl Jam": ("A major", "A – Cadd9 – G riff"),
    "Even Flow|Pearl Jam": ("D major", "D – C funk riff"),
    "Man In the Box|Alice In Chains": ("E minor", "E5 wah riff – G5 – A5"),
    "Would?|Alice In Chains": ("F# minor", "F#m bass riff – B"),
    "Rooster|Alice In Chains": ("B minor", "Bm – G – D – A"),
    "Black Hole Sun|Soundgarden": ("G major", "G – B♭ – F – E♭ – D"),
    "Spoonman|Soundgarden": ("C (drop D)", "C5 – D5 riff 7/4"),
    "Tornado of Souls|Megadeth": ("E minor", "E5 gallop – C – D"),
    "Holy Wars... The Punishment Due|Megadeth": ("E minor", "Em fast riff"),
    "Symphony of Destruction|Megadeth": ("E minor", "E5 – F5 – E5 riff"),
    "Hangar 18|Megadeth": ("A minor", "Am – F – G arpeggios"),
    "Peace Sells|Megadeth": ("E minor", "E5 bass riff"),
    "Paranoid|Black Sabbath": ("E minor", "E5 – D5 – G5 riff"),
    "Iron Man|Black Sabbath": ("B minor", "B5 – D5 – E5 riff"),
    "War Pigs|Black Sabbath": ("E minor", "E5 – D5 swing riff"),
    "N.I.B.|Black Sabbath": ("E minor", "E5 – G5 – A5 riff"),
    "Crazy Train|Ozzy Osbourne": ("F# minor", "F#5 – A – E – D riff"),
    "Mr. Crowley|Ozzy Osbourne": ("D minor", "Dm – A – Gm"),
    "No More Tears|Ozzy Osbourne": ("A minor", "Am bass riff – F – G"),
    "The Trooper|Iron Maiden": ("E minor", "Em – D – C gallop"),
    "Fear of the Dark|Iron Maiden": ("E minor", "Em – C – D – Em"),
    "Hallowed Be Thy Name|Iron Maiden": ("E minor", "Em – D – C – B"),
    "Run to the Hills|Iron Maiden": ("A major", "A – D – G gallop"),
    "Painkiller|Judas Priest": ("E minor", "E5 speed riff"),
    "Breaking the Law|Judas Priest": ("A minor", "Am – F – G riff"),
    "Sultans of Swing|Dire Straits": ("D minor", "Dm – C – B♭ – A"),
    "Money for Nothing|Dire Straits": ("G minor", "Gm – B♭ – C riff"),
    "Brothers In Arms|Dire Straits": ("G# minor", "G#m – E – B – F#"),
    "Hotel California|Eagles": ("B minor", "Bm – F# – A – E – G – D – Em – F#"),
    "Life In the Fast Lane|Eagles": ("E minor", "E7#9 funk riff"),
    "Layla|Derek & The Dominos": ("D minor", "Dm – B♭ – C riff / C#m verses"),
    "Wonderful Tonight|Eric Clapton": ("G major", "G – D/F# – C – D"),
    "Cocaine|Eric Clapton": ("E major", "E – D riff"),
    "Tears In Heaven|Eric Clapton": ("A major", "A – E/G# – F#m – D – E"),
    "Crossroads|Cream": ("A major", "A – D – E blues"),
    "Sunshine of Your Love|Cream": ("D major", "D blues riff – G – A"),
    "White Room|Cream": ("D minor", "Dm – C – G/B – B♭"),
    "The Wind Cries Mary|Jimi Hendrix": ("F major", "E♭ – E – F chromatic"),
    "Texas Flood|Stevie Ray Vaughan": ("G major", "G 12-bar slow blues"),
    "Pride and Joy|Stevie Ray Vaughan": ("E major", "E shuffle 12-bar"),
    "Couldn't Stand the Weather|Stevie Ray Vaughan": ("A minor", "Am funk riff"),
    "Cliffs of Dover|Eric Johnson": ("G major", "G – Em – C – D"),
    "For the Love of God|Steve Vai": ("E minor", "Em – C – Am – B"),
    "Always With Me, Always With You|Joe Satriani": ("B major", "B – G#m – E – F#"),
    "Surfing With the Alien|Joe Satriani": ("G major", "G lydian riff"),
    "Cause We've Ended As Lovers|Jeff Beck": ("C minor", "Cm – A♭ – B♭"),
    "Europa|Santana": ("C minor", "Cm – Fm – B♭ – E♭"),
    "Black Magic Woman|Santana": ("D minor", "Dm – A7 – Gm"),
    "Samba Pa Ti|Santana": ("G major", "G – Em – Am – D"),
    "Sweet Home Alabama|Lynyrd Skynyrd": ("G major", "D – C – G"),
    "Free Bird|Lynyrd Skynyrd": ("G major", "G – D/F# – Em – F – C – D"),
    "Simple Man|Lynyrd Skynyrd": ("A minor", "C – G – Am"),
    "La Grange|ZZ Top": ("A major", "A blues boogie riff"),
    "Sharp Dressed Man|ZZ Top": ("C major", "C5 boogie riff"),
    "Seven Nation Army|The White Stripes": ("E minor", "E – G – E – D – C – B riff"),
    "Do I Wanna Know?|Arctic Monkeys": ("G minor", "Gm – E♭ – B♭ riff"),
    "R U Mine?|Arctic Monkeys": ("F# minor", "F#m – A – E riff"),
    "Lonely Boy|The Black Keys": ("E major", "E – G – A riff"),
    "Gold on the Ceiling|The Black Keys": ("A major", "A – C – D riff"),
    "Out of the Black|Royal Blood": ("F# minor", "F#5 fuzz riff"),
    "Figure It Out|Royal Blood": ("A minor", "Am fuzz riff"),
    "Creep|Radiohead": ("G major", "G – B – C – Cm"),
    "Paranoid Android|Radiohead": ("A minor", "Cm – Gm – A – E"),
    "Karma Police|Radiohead": ("A minor", "Am – D – G – Em"),
    "Wonderwall|Oasis": ("F# minor (capo 2)", "Em7 – G – Dsus4 – A7sus4 shapes"),
    "Don't Look Back In Anger|Oasis": ("C major", "C – F – Am – G"),
    "Where Is My Mind?|Pixies": ("E major", "E – C#m – G# – A"),
    "Zombie|The Cranberries": ("E minor", "Em – C – G – D/F#"),
    "Boulevard of Broken Dreams|Green Day": ("F minor (capo 1)", "Em – G – D – A shapes"),
    "American Idiot|Green Day": ("A♭ major", "A♭5 – D♭5 – E♭5"),
    "Basket Case|Green Day": ("E♭ major", "E♭ – B♭ – Cm – Gm – A♭"),
    "In the End|Linkin Park": ("E♭ minor", "E♭m – B – D♭ – A♭"),
    "Numb|Linkin Park": ("F# minor", "F#m – D – A – E"),
    "Chop Suey!|System of a Down": ("G minor (drop C)", "G5 – A♭5 riff"),
    "Toxicity|System of a Down": ("C minor (drop C)", "C5 riff – E♭ – B♭"),
    "Gravity|John Mayer": ("G major", "G – C/G blues"),
    "Slow Dancing in a Burning Room|John Mayer": ("C# minor", "C#m – A – E – B"),
    "Neon|John Mayer": ("C minor", "C7#9 funk riff"),
    "Tornado of Souls|Megadeth ": ("E minor", "E5 gallop – C – D"),
    "Under the Bridge|Red Hot Chili Peppers": ("E major", "D – F#m – E – B verse"),
    "Californication|Red Hot Chili Peppers": ("A minor", "Am – F – C – G"),
    "Snow (Hey Oh)|Red Hot Chili Peppers": ("G# minor", "G#m – E – B – F# riff"),
    "Otherside|Red Hot Chili Peppers": ("A minor", "Am – F – C – G"),
    "Can't Stop|Red Hot Chili Peppers": ("E minor", "Em funk riff – D – Bm – C"),
    "Scar Tissue|Red Hot Chili Peppers": ("F major", "F – Dm – C"),
    "Plush|Stone Temple Pilots": ("G major", "G – B♭ – C – A♭"),
    "Interstate Love Song|Stone Temple Pilots": ("E major", "E – C#m – A – B"),
    "Bottom|TOOL": ("D minor (drop D)", "D5 grind riff"),
    "Schism|TOOL": ("D minor (drop D)", "Dm riff 5/8+7/8"),
    "Sober|TOOL": ("D minor (drop D)", "D5 – F5 – A5 riff"),
    # ---- Turkish rock canon ----
    "Bir Derdim Var|Mor ve Ötesi": ("E minor", "Em – G – D – A"),
    "Cambaz|Mor ve Ötesi": ("A minor", "Am – F – G – E"),
    "Uyan|Mor ve Ötesi": ("E minor", "Em – C – G – D"),
    "Sevda Çiçeği|Mor ve Ötesi": ("A minor", "Am – G – F – E"),
    "Deli|Mor ve Ötesi": ("B minor", "Bm – G – A – F#"),
    "Sil Baştan|Şebnem Ferah": ("D minor", "Dm – B♭ – F – C"),
    "Bu Aşk Fazla Sana|Şebnem Ferah": ("A minor", "Am – F – C – G"),
    "Sigara|Şebnem Ferah": ("E minor", "Em – C – G – D"),
    "Gündüz Gece|Pentagram": ("A minor", "Am – F – G – E"),
    "Bir|Pentagram": ("E minor", "Em riff – C – D"),
    "Senden Daha Güzel|Duman": ("F# minor", "F#m – D – A – E"),
    "Belki Alışman Lazım|Duman": ("B minor", "Bm – G – D – A"),
    "Her Şeyi Yak|Duman": ("E minor", "Em – G – D – A"),
    "Bu Akşam|Duman": ("A minor", "Am – F – C – G"),
    "Köprüaltı|Duman": ("E minor", "Em – C – G – D"),
    "İstanbul'da Sonbahar|Teoman": ("A minor", "Am – Dm – E – Am"),
    "Papatya|Teoman": ("E minor", "Em – Am – B7"),
    "Paramparça|Teoman": ("D minor", "Dm – B♭ – C – A"),
    "Susuz Aşk|Kargo": ("B minor", "Bm – G – A – F#"),
    "Yıldızların Altında|Kargo": ("E minor", "Em – C – D – Bm"),
    "Anlasana|Feridun Düzağaç": ("A minor", "Am – F – G – E"),
    "Beni Bırakma|Feridun Düzağaç": ("E minor", "Em – C – G – D"),
    "Toz|Gripin": ("B minor", "Bm – G – D – A"),
    "Aşk Nereden Nereye|Gripin": ("E minor", "Em – C – G – D"),
    "Sen Gidiyorsun|Gripin": ("A minor", "Am – F – C – G"),
    "Dönence|Barış Manço": ("A minor", "Am – G – F – E"),
    "Gülpembe|Barış Manço": ("D minor", "Dm – C – B♭ – A"),
    "Kayaların Oğlu|Cem Karaca": ("D minor", "Dm – Gm – A"),
    "Tamirci Çırağı|Cem Karaca": ("A minor", "Am – Dm – E"),
    "Resimdeki Gözyaşları|Cem Karaca": ("E minor", "Em – Am – B7"),
    "Lambaya Püf De|Erkin Koray": ("A minor", "Am psych riff"),
    "Cemalim|Erkin Koray": ("D minor", "Dm – C – B♭"),
    "Ve Ölüm|Erkin Koray": ("E minor", "Em – D – C"),
    "Yine Yol Göründü Gurbete|Moğollar": ("A minor", "Am – G – F"),
    "Bin Boğanın Kızı|Moğollar": ("D minor", "Dm – C – B♭ – A"),
}


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    return s.lower().replace("ı", "i").strip()


def main() -> None:
    path = sys.argv[1] if len(sys.argv) > 1 else "ToneAmp/SeedCatalog.json"
    songs = json.load(open(path))
    table = {norm(k): v for k, v in K.items()}
    hit = 0
    for song in songs:
        entry = table.get(norm(f"{song['title']}|{song['artist']}"))
        if entry:
            song["key"], song["chords"] = entry
            hit += 1
    json.dump(songs, open(path, "w"), ensure_ascii=False, indent=1)
    print(f"keys/chords applied to {hit}/{len(songs)} songs")


if __name__ == "__main__":
    main()
