#!/usr/bin/env python3
"""Overwrites template starter tones in SeedCatalog.json with hand-researched
per-song rigs ("gold tones"). Keyed by "Title|Artist"; matching is
normalization-tolerant. Usage: apply_gold_tones.py SeedCatalog.json
Entry: (tone_name, character, amp, (gain,bass,mid,treble,presence,reverb),
        guitar, pickup, [(pedal, type, [(knob, val)...], note)...], notes)
"""
import json
import re
import sys

TRANSLIT = str.maketrans("çğıöşüÇĞİÖŞÜâîûÂÎÛ", "cgiosuCGIOSUaiuAIU")


def norm(s):
    return re.sub(r"[^a-z0-9]+", " ", s.translate(TRANSLIT).lower()).strip()


G = {
# ---------- HENDRIX / 60s ----------
"Voodoo Child (Slight Return)|Jimi Hendrix": [("Main (Wah + Fuzz)","Fuzz","Marshall Super Lead 100",(6,5.5,6,6.5,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Vox Wah","wah",[],"Rocked through the intro — the wah IS the riff"),("Dallas Arbiter Fuzz Face","fuzz",[("Fuzz",8),("Volume",7)],"Germanium fuzz; clean up with the guitar volume")],"Tuned down a half step. Intro is muted wah scratching before the riff lands.")],
"Little Wing|Jimi Hendrix": [("Clean Rhythm","Clean","Fender Twin Reverb",(3,5.5,5.5,6,4.5,4),"Fender Stratocaster","Neck single-coil",[("Leslie / Univibe","chorus",[("Speed",3),("Depth",6)],"The swirl on the record is a rotating speaker — a Uni-Vibe gets you close")],"Thumb-over chord embellishments; hammer-ons inside chords do the singing.")],
"All Along the Watchtower|Jimi Hendrix": [("Main","Overdrive","Marshall Super Lead 100",(5.5,5.5,6,6.5,5,2),"Fender Stratocaster","Bridge single-coil",[("Vox Wah","wah",[],"Solo sections — slow sweeps as a tone filter"),("Dallas Arbiter Fuzz Face","fuzz",[("Fuzz",6.5),("Volume",6.5)],"Kicked in for solo peaks")],"Half-step down. Layered solos: slide, wah, and octave phrases each get a verse.")],
"Hey Joe|Jimi Hendrix": [("Main","Overdrive","Marshall Super Lead 100",(5,5.5,6,6,5,2.5),"Fender Stratocaster","Bridge single-coil",[],"Amp edge-of-breakup only; the double-stop fills answer every vocal line.")],
"Foxey Lady|Jimi Hendrix": [("Main","Fuzz","Marshall Super Lead 100",(6,5.5,6,6.5,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Dallas Arbiter Fuzz Face","fuzz",[("Fuzz",8.5),("Volume",7)],"The feedback intro is the fuzz + volume swell into the amp")],"Hold the opening note against the amp for the feedback bloom.")],
"Sunshine of Your Love|Cream": [("Main","Fuzz","Marshall Super Lead (Plexi)",(6.5,5.5,6.5,6,5,0),"Gibson SG","Neck humbucker",[],"Clapton's 'woman tone': neck pickup with the tone knob rolled almost fully off, cranked Marshall.")],
"White Room|Cream": [("Main","Fuzz","Marshall Super Lead (Plexi)",(6.5,5.5,6,6,5,0),"Gibson SG","Bridge humbucker",[("Vox Wah","wah",[],"The whole solo rides the wah")],"Verse chords big and open; the outro solo is continuous wah phrasing.")],
"Crossroads|Cream": [("Live Lead","Overdrive","Marshall Super Lead (Plexi)",(6,5.5,6.5,6.5,5.5,0),"Gibson ES-335","Bridge humbucker",[],"No pedals — a loud Plexi and precise picking. Solo lines land right on the beat.")],
"(I Can't Get No) Satisfaction|The Rolling Stones": [("Fuzz Riff","Fuzz","Vox AC30",(4,5,5.5,6,4.5,1.5),"Gibson Les Paul","Bridge humbucker",[("Maestro FZ-1 Fuzz-Tone","fuzz",[("Attack",8),("Volume",6)],"The riff that sold the world on fuzz — sputtery and horn-like")],"Keep the amp clean; the FZ-1 does everything.")],
"Jumpin' Jack Flash|The Rolling Stones": [("Main","Crunch","Vox AC30",(5.5,5,5.5,6.5,5,1.5),"Fender Telecaster","Bridge single-coil",[],"Open tunings and capos define Richards' voicings — the grind is all amp.")],
"Gimme Shelter|The Rolling Stones": [("Intro","Clean","Fender Twin Reverb",(3.5,5,5.5,6,4.5,4.5),"Fender Telecaster","Bridge single-coil",[("Tremolo","chorus",[("Rate",4),("Depth",5)],"The shivering intro is amp tremolo")],"Open-E tuning arpeggios; let every string bleed together.")],
"Start Me Up|The Rolling Stones": [("Main","Crunch","Mesa/Boogie Mark I",(5.5,5,6,6.5,5,1),"Fender Telecaster","Bridge single-coil",[],"Open-G tuning, five strings, no pedals — mute with the palm and snap the chords.")],
"Brown Sugar|The Rolling Stones": [("Main","Crunch","Ampeg VT-40",(5.5,5,6,6.5,5,1),"Fender Telecaster","Bridge single-coil",[],"Open-G tuning; the slides between chord shapes are the hook.")],
"While My Guitar Gently Weeps|The Beatles": [("Lead","Overdrive","Fender Twin Reverb",(5.5,5.5,6,6,5,2),"Gibson Les Paul","Bridge humbucker",[],"Clapton's uncredited lead — singing bends with heavy vibrato, tone rolled slightly back.")],
"Come Together|The Beatles": [("Main","Clean","Fender Twin Reverb",(3.5,6,5,5.5,4.5,2.5),"Gibson Les Paul? Epiphone Casino","Neck pickup",[("Tremolo","chorus",[("Rate",3.5),("Depth",4)],"Subtle shimmer on the swampy riff")],"Play the riff with a dark neck tone and let the bass carry the low end.")],
"Helter Skelter|The Beatles": [("Main","Fuzz","Vox Conqueror",(7,5.5,5.5,6,5,0),"Epiphone Casino","Bridge pickup",[("Tone Bender","fuzz",[("Attack",8),("Level",6)],"Everything cranked into breakup")],"Sloppy on purpose — dig in hard and let the amp scream.")],
"Taxman|The Beatles": [("Main","Crunch","Vox AC30",(5,5,5.5,6.5,5,1),"Epiphone Casino","Bridge pickup",[],"McCartney's solo: aggressive Indian-flavored bends on a cranked AC30.")],
"Revolution|The Beatles": [("Fuzz Rhythm","Fuzz","Direct into console",(9,5.5,5.5,6,5,0),"Epiphone Casino","Bridge pickup",[],"The famous tone is guitars plugged straight into an overloaded mixing desk — recreate with a cranked fuzz into a clean amp.")],
"Day Tripper|The Beatles": [("Riff","Crunch","Vox AC30",(4.5,5,5.5,6.5,5,1.5),"Fender Stratocaster","Bridge single-coil",[],"The riff doubles in octaves as the song builds — keep it clean enough to articulate.")],
"Paperback Writer|The Beatles": [("Riff","Crunch","Vox AC30",(5,5.5,5.5,6,5,1),"Epiphone Casino","Bridge pickup",[],"Boosted bass-heavy riff; snap the strings hard.")],
"Get Back|The Beatles": [("Main","Clean","Fender Twin Reverb",(3.5,5,5.5,6,4.5,2),"Fender Telecaster","Bridge single-coil",[],"Rooftop tone: a Twin just starting to sweat, all feel.")],
"My Generation|The Who": [("Main","Crunch","Marshall JTM45",(5.5,5.5,5.5,6,5,1),"Fender Stratocaster","Bridge single-coil",[],"Slashing full chords — Townshend's rhythm IS the lead.")],
"Won't Get Fooled Again|The Who": [("Main","Crunch","Hiwatt CP103",(5.5,5.5,6,6.5,5.5,1),"Gibson SG Special","Bridge pickup",[],"Big open-position chords over the synth; hit them like cymbals.")],
"Baba O'Riley|The Who": [("Main","Crunch","Hiwatt CP103",(5.5,5.5,6,6.5,5.5,1),"Gibson SG Special","Bridge pickup",[],"Power chords enter like an avalanche after the synth intro — no subtlety wanted.")],
"Pinball Wizard|The Who": [("Electric Layer","Crunch","Hiwatt CP103",(5,5.5,5.5,6.5,5,1),"Gibson SG Special","Bridge pickup",[],"Doubles the acoustic flamenco strumming with crunchy stabs.")],
"Fortunate Son|Creedence Clearwater Revival": [("Main","Crunch","Kustom K200",(5,5.5,6,6,4.5,1.5),"Gibson Les Paul Custom","Bridge humbucker",[],"Dry, punchy, mid-forward — no effects, just attitude and downstrokes.")],
"Born on the Bayou|Creedence Clearwater Revival": [("Main","Crunch","Kustom K200",(4.5,5.5,6,5.5,4.5,2.5),"Rickenbacker 325","Bridge pickup",[("Tremolo","chorus",[("Rate",3),("Depth",5)],"Swamp shimmer on the E7 vamp")],"One chord, infinite groove — it's all in the right hand.")],

# ---------- ZEPPELIN / PURPLE / SABBATH / 70s ----------
"Stairway to Heaven|Led Zeppelin": [("Intro (Clean)","Clean","Fender Deluxe? Supro Coronado",(3,5.5,5.5,5.5,4.5,2.5),"Fender Telecaster","Neck single-coil",[],"Fingerpicked arpeggios; let adjacent strings ring into each other."),("Solo","Lead","Marshall Super Lead (Plexi)",(6.5,5.5,6.5,6.5,5.5,0),"Fender Telecaster","Bridge single-coil",[],"The solo is a Telecaster, not a Les Paul — cutting, vocal, every phrase answered.")],
"Kashmir|Led Zeppelin": [("Main","Crunch","Marshall Super Lead (Plexi)",(5.5,6,6,6,5,1),"Gibson Les Paul","Bridge humbucker",[],"DADGAD tuning. The riff is a loop — lock to the drums, not the orchestra.")],
"Black Dog|Led Zeppelin": [("Main","Crunch","Marshall Super Lead (Plexi)",(6,5.5,6.5,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Recorded through a direct box into compressors — a mid-heavy cranked Marshall gets you there.")],
"Immigrant Song|Led Zeppelin": [("Main","Crunch","Marshall Super Lead (Plexi)",(6,5.5,6.5,6,5,0),"Gibson Les Paul","Bridge humbucker",[],"Gallop with strict palm muting; the octave stabs must snap.")],
"Rock and Roll|Led Zeppelin": [("Main","Crunch","Marshall Super Lead (Plexi)",(6,5.5,6,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Straight 12-bar fire; solo is pure pentatonic release.")],
"Heartbreaker|Led Zeppelin": [("Main","Crunch","Marshall Super Lead (Plexi)",(6.5,5.5,6.5,6,5,0),"Gibson Les Paul","Bridge humbucker",[],"The unaccompanied solo break: loose, wild, human — don't quantize it.")],
"Since I've Been Loving You|Led Zeppelin": [("Blues Lead","Overdrive","Marshall Super Lead (Plexi)",(5.5,5.5,6,6,5,2),"Gibson Les Paul","Neck humbucker",[],"Dynamics from a whisper to a scream — ride the guitar volume all song.")],
"Ramble On|Led Zeppelin": [("Verse (Clean)","Clean","Supro Coronado",(3,5.5,5.5,5.5,4.5,2),"Fender Telecaster","Neck single-coil",[],"Gentle verse picking against the bass melody; save the grind for the chorus.")],
"Achilles Last Stand|Led Zeppelin": [("Main","Crunch","Marshall Super Lead (Plexi)",(6.5,5.5,6,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Galloping E-minor orchestra of overdubs — pick one line and commit.")],
"Dazed and Confused|Led Zeppelin": [("Main","Overdrive","Marshall Super Lead (Plexi)",(5.5,6,6,6,5,2),"Fender Telecaster","Bridge single-coil",[("Vox Wah","wah",[],"Mid-section textures"),],"Descending chromatic dread; the bowed section is texture — a slide or EBow approximates it.")],
"Highway Star|Deep Purple": [("Main","Crunch","Marshall Major 200",(6,5,5.5,7,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Hornby Skewes Treble Booster","boost",[("Boost",7)],"Always on — Blackmore's edge")],"The solo is Bach-like sequences — alternate pick every note, no legato shortcuts.")],
"Burn|Deep Purple": [("Main","Crunch","Marshall Major 200",(6,5,5.5,7,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Hornby Skewes Treble Booster","boost",[("Boost",7)],"Always on")],"Fast riff in G minor — mute between stabs so the horns of the riff stay clean.")],
"Lazy|Deep Purple": [("Main","Overdrive","Marshall Major 200",(5.5,5,5.5,6.5,5.5,1),"Fender Stratocaster","Bridge single-coil",[("Hornby Skewes Treble Booster","boost",[("Boost",6.5)],"Always on")],"A blues shuffle disguised as a jam — swing it hard.")],
"Black Night|Deep Purple": [("Main","Crunch","Marshall Major 200",(5.5,5,5.5,6.5,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Hornby Skewes Treble Booster","boost",[("Boost",7)],"Always on")],"The riff is borrowed blues — accent the pickup notes into each bar.")],
"Perfect Strangers|Deep Purple": [("Main","Crunch","Marshall Major 200",(5.5,5.5,5.5,6.5,5.5,0),"Fender Stratocaster","Bridge single-coil",[],"Slow, ceremonial riff — let each chord breathe a full bar.")],
"Iron Man|Black Sabbath": [("Main","Crunch","Laney Supergroup LA100BL",(6,5,6,6.5,5,0),"Gibson SG","Bridge humbucker",[("Dallas Rangemaster","boost",[("Boost",8)],"Treble booster slicing the Laney")],"Bend into every riff note — Iommi's light-gauge strings and downtuned menace.")],
"War Pigs|Black Sabbath": [("Main","Crunch","Laney Supergroup LA100BL",(6,5,6,6.5,5,0),"Gibson SG","Bridge humbucker",[("Dallas Rangemaster","boost",[("Boost",8)],"Always on")],"Space is the riff — those silences between chords are load-bearing.")],
"N.I.B.|Black Sabbath": [("Main","Crunch","Laney Supergroup LA100BL",(6,5.5,6,6,5,0),"Gibson SG","Bridge humbucker",[("Dallas Rangemaster","boost",[("Boost",7.5)],"Always on")],"Follow the bassline riff exactly — guitar and bass in lockstep.")],
"Children of the Grave|Black Sabbath": [("Main","Crunch","Laney Supergroup LA100BL",(6.5,5.5,6,6.5,5,0),"Gibson SG","Bridge humbucker",[("Dallas Rangemaster","boost",[("Boost",8)],"Always on")],"C# tuning gallop — palm-muted triplets with the toms.")],
"Sweet Leaf|Black Sabbath": [("Main","Crunch","Laney Supergroup LA100BL",(6.5,6,6,6,5,0),"Gibson SG","Bridge humbucker",[("Dallas Rangemaster","boost",[("Boost",7.5)],"Always on")],"C# tuning; riff drags slightly behind the beat — that's the doom.")],
"Heaven and Hell|Black Sabbath": [("Main","Crunch","Laney Supergroup LA100BL",(6.5,5.5,6,6.5,5.5,0),"Gibson SG","Bridge humbucker",[],"Dio-era polish: tighter palm mutes, singing sustain on the melody line.")],
"Free Bird|Lynyrd Skynyrd": [("Slide & Outro","Lead","Peavey Mace",(6,5.5,6,6.5,5.5,2),"Gibson SG","Bridge humbucker",[],"Slide verses in open E feel; the outro is twin-guitar harmony — record one, play the other.")],
"Sweet Home Alabama|Lynyrd Skynyrd": [("Main","Clean","Peavey Mace",(3.5,5,5.5,6.5,5,2.5),"Fender Stratocaster","Middle + bridge (position 2)",[],"The D–C–G turnaround with chicken-pickin' fills — snap the strings off the fretboard.")],
"Simple Man|Lynyrd Skynyrd": [("Main","Clean","Peavey Mace",(3.5,5.5,5.5,5.5,4.5,3),"Gibson Les Paul","Neck humbucker",[],"Arpeggiated C–G–Am forever; the solo stays inside the vocal melody.")],
"More Than a Feeling|Boston": [("Main","Crunch","Custom Scholz rig (Marshall + attenuator)",(6.5,5.5,6.5,6,5,1),"Gibson Les Paul","Bridge humbucker",[("Rockman-style Compressor","compressor",[("Sustain",7)],"Scholz's studio-perfect sustain and double-tracking")],"Layered precision — every bend lands exactly in tune, doubled.")],
"Tom Sawyer|Rush": [("Main","Crunch","Marshall JCM800? Hiwatt",(5.5,5.5,6,6.5,5.5,1.5),"Fender Stratocaster (modded)","Bridge humbucker",[("Electric Mistress","flanger",[("Rate",2.5),("Range",5),("Color",4.5)],"Lifeson's watery chord shimmer")],"Suspended chords ring over the synth — never plain barre shapes.")],
"The Spirit of Radio|Rush": [("Intro","Crunch","Marshall JCM800? Hiwatt",(5.5,5,5.5,7,5.5,1.5),"Gibson ES-355","Bridge humbucker",[],"The intro lick is a hammer-on cascade — keep it bright and bouncing.")],
"Limelight|Rush": [("Main","Crunch","Marshall + Hiwatt blend",(5.5,5.5,6,6.5,5.5,1.5),"Fender Stratocaster (modded)","Bridge humbucker",[("Electric Mistress","flanger",[("Rate",2.5),("Range",5),("Color",4.5)],"On for the chorus wash")],"The solo floats free of the beat — long bends with wide vibrato.")],
"YYZ|Rush": [("Main","Crunch","Marshall + Hiwatt blend",(6,5.5,6,6.5,5.5,1)," Fender Stratocaster (modded)","Bridge humbucker",[],"Unison riffing with bass in 5/4 morse code — precision over power.")],
"Hotel California|Eagles": None,  # curated version exists
"Life in the Fast Lane|Eagles": [("Main","Crunch","Fender Tweed Deluxe",(5.5,5,6,6.5,5,1),"Gibson Les Paul","Bridge humbucker",[("Talk Box? none","eq",[],"The riff is dry and funky — no effects needed")],"Walsh's riff: staccato and greasy, right behind the beat.")],
"Take It Easy|Eagles": [("Main","Clean","Fender Twin Reverb",(3,5,5.5,6.5,5,2.5),"Fender Telecaster","Bridge single-coil",[],"Country-rock strumming with banjo-roll fills — bright and open.")],

# ---------- VAN HALEN / 80s HARD ROCK & METAL ----------
"Eruption|Van Halen": [("Solo","Lead","Marshall Super Lead (Variac'd)",(7.5,5.5,6,6.5,6,1.5),"Frankenstrat","Bridge humbucker",[("MXR Phase 90","phaser",[("Speed",3.5)],"The swirl over the tapping"),("Echoplex EP-3","delay",[("Time",4),("Repeats",3),("Mix",3)],"Depth on the dive bombs")],"The 'brown sound': Plexi on a Variac at ~90V, cranked everything. Tapping section is all legato confidence.")],
"Runnin' with the Devil|Van Halen": [("Main","Crunch","Marshall Super Lead (Variac'd)",(6.5,5.5,6,6.5,6,1.5),"Frankenstrat","Bridge humbucker",[("MXR Phase 90","phaser",[("Speed",3)],"Subtle motion on the chords")],"Big lazy chords — let them hang and shimmer.")],
"Panama|Van Halen": [("Main","Crunch","Marshall Super Lead (Variac'd)",(7,5.5,6,6.5,6,1.5),"Frankenstrat","Bridge humbucker",[],"Slide into every chord; the breakdown rides the guitar volume knob.")],
"Ain't Talkin' 'bout Love|Van Halen": [("Main","Crunch","Marshall Super Lead (Variac'd)",(7,5.5,6,6.5,6,1.5),"Frankenstrat","Bridge humbucker",[("MXR Phase 90","phaser",[("Speed",3.5)],"On the arpeggio riff")],"Am arpeggio with attitude — dig in on the open strings.")],
"Hot for Teacher|Van Halen": [("Main","Lead","Marshall Super Lead (Variac'd)",(7.5,5.5,6,6.5,6,1.5),"Frankenstrat","Bridge humbucker",[],"The intro is tapped triplets over a shuffle — swing it or it dies.")],
"Unchained|Van Halen": [("Main","Crunch","Marshall Super Lead (Variac'd)",(7,5.5,6,6.5,6,1.5),"Frankenstrat","Bridge humbucker",[("MXR Flanger","flanger",[("Rate",2),("Range",6),("Color",5)],"THE flanger chord — full sweep on the drop-D riff")],"Drop D. The flanger swoosh on the main riff is the song's signature.")],
"Crazy Train|Ozzy Osbourne": [("Main","High Gain","Marshall 1959RR (modded)",(7.5,5.5,5.5,6.5,6,0),"Jackson? Karl Sandoval Polka-Dot V","Bridge humbucker",[("MXR Distortion+","distortion",[("Distortion",6),("Output",6)],"Rhoads' extra saturation into the Marshall"),("MXR Stereo Chorus","chorus",[("Rate",3),("Depth",5)],"Widens the riff subtly")],"F# minor riff — classical precision, every note picked.")],
"Mr. Crowley|Ozzy Osbourne": [("Solo","Lead","Marshall 1959RR (modded)",(7.5,5.5,6,6.5,6,1),"Gibson Les Paul Custom","Bridge humbucker",[("MXR Distortion+","distortion",[("Distortion",6.5),("Output",6)],"Singing lead saturation")],"The outro solo is Rhoads' masterclass: fast scalar runs resolving to huge bends.")],
"Flying High Again|Ozzy Osbourne": [("Main","High Gain","Marshall 1959RR (modded)",(7,5.5,5.5,6.5,6,0),"Jackson? Sandoval V","Bridge humbucker",[("MXR Distortion+","distortion",[("Distortion",6),("Output",6)],"Always on")],"Tapped solo section — mute the unused strings with the picking hand.")],
"Bark at the Moon|Ozzy Osbourne": [("Main","High Gain","Marshall JCM800",(7.5,5.5,5.5,7,6,0),"Charvel San Dimas","Bridge humbucker",[("Boss OD-1","boost",[("Level",7),("Drive",2)],"Tightens the JCM800")],"Jake E. Lee era: sharper, faster picking than the Rhoads years.")],
"No More Tears|Ozzy Osbourne": [("Main","High Gain","Marshall JCM800",(7.5,6,5.5,6.5,6,0),"Gibson Les Paul Custom","Bridge humbucker",[("Boss SD-1","boost",[("Drive",2),("Level",7)],"Wylde's always-on tightener"),("MXR Chorus","chorus",[("Rate",3),("Depth",4)],"On the clean interlude")],"Zakk's pinch harmonics squeal on every riff repeat.")],
"Holy Diver|Dio": [("Main","Crunch","Marshall Super Lead",(6.5,5.5,6,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"Campbell's riff: even eighths, no swing, menace from restraint.")],
"Rainbow in the Dark|Dio": [("Main","Crunch","Marshall Super Lead",(6.5,5.5,6,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"Riff mirrors the synth hook — stay tight against it.")],
"Since You Been Gone|Rainbow": [("Main","Crunch","Marshall Major 200",(6,5,5.5,7,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Treble Booster","boost",[("Boost",7)],"Blackmore's edge")],"Pop-rock chords played like a riff — punch every change.")],
"Stargazer|Rainbow": [("Main","Crunch","Marshall Major 200",(6,5.5,5.5,6.5,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Treble Booster","boost",[("Boost",7)],"Always on")],"Eastern-tinged solo over the orchestra — bend to the scale, not the blues.")],
"Man on the Silver Mountain|Rainbow": [("Main","Crunch","Marshall Major 200",(6,5,5.5,6.5,5.5,0),"Fender Stratocaster","Bridge single-coil",[("Treble Booster","boost",[("Boost",7)],"Always on")],"The riff is a chant — same four notes, total conviction.")],
"Rock You Like a Hurricane|Scorpions": [("Main","Crunch","Marshall JCM800",(6.5,5.5,5.5,6.5,5.5,0),"Gibson Explorer? Flying V","Bridge humbucker",[],"The pre-chorus mutes are the tension; release fully open on the chorus.")],
"Still Loving You|Scorpions": [("Lead","Lead","Marshall JCM800",(6.5,5.5,6.5,6,5.5,2),"Fender Stratocaster","Bridge humbucker",[("Delay","delay",[("Time",4.5),("Repeats",3),("Mix",3)],"Space around the intro melody")],"Clean arpeggios build to full-gain climax — one long crescendo.")],
"Wind of Change|Scorpions": [("Clean + Lead","Clean","Fender Twin Reverb",(3,5.5,5.5,6,5,3.5),"Fender Stratocaster","Neck single-coil",[("Chorus","chorus",[("Rate",3),("Depth",4.5)],"90s gloss on the cleans")],"Whistled melody answered by clean arpeggios; solo switches to smooth drive.")],
"Pour Some Sugar on Me|Def Leppard": [("Main","Crunch","Rockman + Marshall blend",(6.5,5.5,5.5,6.5,5.5,1),"Jackson Soloist","Bridge humbucker",[("Compressor","compressor",[("Sustain",6.5)],"Mutt Lange studio squash — everything even")],"Layered chord stacks — precision over aggression.")],
"Photograph|Def Leppard": [("Main","Crunch","Marshall JCM800",(6.5,5.5,5.5,6.5,5.5,1),"Jackson Soloist","Bridge humbucker",[],"Bright chorused stacks; the solo is pure melody, no shredding.")],
"Hysteria|Def Leppard": [("Main","Clean","Rockman",(3,5.5,5,6,5,3),"Jackson Soloist","Bridge humbucker",[("Chorus","chorus",[("Rate",3),("Depth",5)],"The glassy arpeggio sheen"),("Delay","delay",[("Time",4),("Repeats",3),("Mix",3.5)],"Every note blooms")],"Arpeggios like a music box — absolute evenness.")],
"Livin' on a Prayer|Bon Jovi": [("Main","Crunch","Marshall JCM800",(6,5.5,5.5,6.5,5.5,1),"Kramer? Jackson","Bridge humbucker",[("Talk Box","wah",[],"THE talk box riff — Heil Talk Box into a mic"),],"Verse rides the talk box; chorus opens to full chords.")],
"You Give Love a Bad Name|Bon Jovi": [("Main","Crunch","Marshall JCM800",(6.5,5.5,5.5,6.5,5.5,1),"Kramer? Jackson","Bridge humbucker",[],"A cappella intro chords — hit them like a gang vocal.")],
"Wanted Dead or Alive|Bon Jovi": [("Intro","Clean","Fender Twin Reverb",(3,5.5,5.5,6,5,3),"Ovation? 12-string electric","Neck pickup",[("Chorus","chorus",[("Rate",3),("Depth",5)],"12-string sparkle")],"The intro run mixes open strings with fretted unisons — let them clash.")],
"It's My Life|Bon Jovi": [("Main","High Gain","Marshall JCM2000",(7,5.5,5.5,6.5,5.5,0),"Fender Telecaster (modded)","Bridge humbucker",[("Talk Box","wah",[],"Modern talk box on the riff")],"Drop-D chug under the talk box hook.")],
"Here I Go Again|Whitesnake": [("Main","Crunch","Marshall JCM800",(6.5,5.5,6,6.5,5.5,1),"Gibson Les Paul","Bridge humbucker",[],"87 version: big polished chords, sustained bends in the solo.")],
"Still of the Night|Whitesnake": [("Main","Crunch","Marshall JCM800",(7,5.5,6,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Sykes' huge riff — Zeppelin scale, 80s gain, violent vibrato.")],
"The Final Countdown|Europe": [("Solo","Lead","Marshall JCM800",(7,5.5,6,6.5,5.5,1.5),"Fender Stratocaster (modded)","Bridge humbucker",[("Delay","delay",[("Time",4),("Repeats",3),("Mix",3)],"Norum's singing sustain")],"The solo outshines the synth hook — fast alternate picking into soaring bends.")],
"The Boys Are Back in Town|Thin Lizzy": [("Harmony Leads","Crunch","Marshall Super Lead",(6,5.5,6,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Twin harmonies in thirds — the Thin Lizzy signature; record both parts.")],
"Jailbreak|Thin Lizzy": [("Main","Crunch","Marshall Super Lead",(6,5.5,6,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Staccato riff stabs; mute hard between hits.")],
"Ace of Spades|Motörhead": [("Main","Crunch","Marshall Super Lead",(7,5.5,6,6.5,5.5,0),"Gibson Les Paul? Rickenbacker",  "Bridge humbucker",[],"Everything past 10 — speed and filth over precision.")],
"Overkill|Motörhead": [("Main","Crunch","Marshall Super Lead",(7,5.5,6,6.5,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Double-kick freight train; chords are just percussion here.")],

# ---------- METALLICA & THRASH ----------
"Master of Puppets|Metallica": [("Rhythm","High Gain","Mesa/Boogie Mark IIC+",(8.5,6.5,3,7,6,0),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[("Ibanez Tube Screamer","boost",[("Drive",1),("Tone",5),("Level",8.5)],"Clean boost tightening the chug")],"All downstrokes at 212 BPM — build stamina before speed."),("Interlude (Clean)","Clean","Roland JC-120",(2.5,5.5,5,5.5,4.5,3),"ESP Explorer (EMG 60)","Neck humbucker (active)",[("Chorus","chorus",[("Rate",3),("Depth",5)],"JC-120 built-in shimmer")],"The clean middle section — arpeggios with volume swells.")],
"One|Metallica": [("Intro (Clean)","Clean","Roland JC-120",(2.5,5.5,5,5.5,4.5,3),"ESP (EMG 60)","Neck humbucker (active)",[("Chorus","chorus",[("Rate",3),("Depth",4.5)],"Cold clean shimmer")],"Clean arpeggios in B minor — sparse and funereal."),("Outro (Kick Riff)","High Gain","Mesa/Boogie Mark IIC+",(8.5,6.5,3,7,6,0),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[("Tube Screamer","boost",[("Drive",1),("Level",8.5)],"Tightening boost")],"The machine-gun section doubles the double-kick exactly.")],
"Sad but True|Metallica": [("Main","High Gain","Mesa/Boogie Mark IIC+ into Marshall",(8,6.5,4,6.5,6,0),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[("Tube Screamer","boost",[("Drive",1),("Level",8)],"Tightener")],"D standard tuning — the heaviest slow riff in the catalog; leave space.")],
"Fade to Black|Metallica": [("Intro (Clean)","Clean","Roland JC-120",(2.5,5.5,5,5.5,4.5,3.5),"ESP (EMG 60)","Neck humbucker (active)",[],"Arpeggiated Bm — the acoustic feel comes from even dynamics."),("Outro Solo","Lead","Mesa/Boogie Mark IIC+",(8,6,4.5,6.5,6,1),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[],"Hammett's fastest melodic playing — loops of pull-offs that climb forever.")],
"Battery|Metallica": [("Main","High Gain","Mesa/Boogie Mark IIC+",(8.5,6.5,3,7,6,0),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[("Tube Screamer","boost",[("Drive",1),("Level",8.5)],"Tightener")],"Acoustic intro then total war — downstrokes only.")],
"Creeping Death|Metallica": [("Main","High Gain","Mesa/Boogie Mark IIC+",(8.5,6.5,3.5,7,6,0),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[("Tube Screamer","boost",[("Drive",1),("Level",8.5)],"Tightener")],"The 'Die!' chug section: single palm-muted E, pure crowd fuel.")],
"Seek & Destroy|Metallica": [("Main","High Gain","Marshall JCM800",(7.5,6,4.5,6.5,5.5,0),"Gibson Flying V","Bridge humbucker",[],"Kill 'Em All era: rawer, less scooped than later records.")],
"Fuel|Metallica": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(8,6.5,4,6.5,6,0),"ESP Explorer (EMG 81)","Bridge humbucker (active)",[],"Load-era grind: slower gain, more sludge in the mids.")],
"The Unforgiven|Metallica": [("Verse (Clean)","Clean","Roland JC-120",(2.5,5.5,5,5.5,4.5,3),"ESP (EMG 60)","Neck humbucker (active)",[],"Am arpeggios under the vocal; the chorus flips heavy — set both sounds up.")],
"Holy Wars... The Punishment Due|Megadeth": [("Main","High Gain","Marshall JCM800 (modded)",(8,6,4.5,7,6,0),"Jackson King V","Bridge humbucker",[],"Mustaine's spider-chord riffing — economy of motion, brutal precision.")],
"Hangar 18|Megadeth": [("Main + Solos","High Gain","Marshall JCM800 (modded)",(8,6,5,7,6,0),"Jackson King V","Bridge humbucker",[],"Trading solos every four bars — each one raises the stakes.")],
"Symphony of Destruction|Megadeth": [("Main","High Gain","Marshall JCM800 (modded)",(7.5,6,5,6.5,6,0),"Jackson King V","Bridge humbucker",[],"Mid-tempo stomp — the riff is a march, not a sprint.")],
"Tornado of Souls|Megadeth": [("Solo","Lead","Marshall JCM800 (modded)",(8,6,5.5,6.5,6,1),"Jackson Soloist","Bridge humbucker",[],"Friedman's solo: exotic bends approached from below, phrased like a vocalist.")],
"Peace Sells|Megadeth": [("Main","High Gain","Marshall JCM800 (modded)",(7.5,6,5,7,6,0),"Jackson King V","Bridge humbucker",[],"The bass owns the intro; guitar answers with snarling stabs.")],
"Raining Blood|Slayer": [("Main","High Gain","Marshall JCM800 (modded)",(8.5,6,4,7,6.5,0),"B.C. Rich? Jackson","Bridge humbucker",[],"Tremolo-picked chaos — the dive bombs at the end are free-fall, no rules.")],
"Angel of Death|Slayer": [("Main","High Gain","Marshall JCM800 (modded)",(8.5,6,4,7,6.5,0),"B.C. Rich? Jackson","Bridge humbucker",[],"The scream, the gallop, the whammy abuse — maximum violence, minimum reverb.")],
"South of Heaven|Slayer": [("Main","High Gain","Marshall JCM800 (modded)",(8,6,4.5,6.5,6,0),"B.C. Rich? Jackson","Bridge humbucker",[],"Slayer slowed down is scarier — let the intro riff crawl.")],
"Cowboys from Hell|Pantera": [("Main","High Gain","Randall RG100 (solid-state)",(8.5,6,3.5,7.5,6.5,0),"Dean ML","Bridge humbucker (Bill Lawrence L-500XL)",[("MXR 6-Band EQ","eq",[("Mid cut",3)],"Dimebag's scooped solid-state grind")],"The groove is between the notes — mute everything that isn't the riff.")],
"Walk|Pantera": [("Main","High Gain","Randall RG100 (solid-state)",(8.5,6,3.5,7.5,6.5,0),"Dean ML","Bridge humbucker (L-500XL)",[("MXR 6-Band EQ","eq",[("Mid cut",3)],"Scooped razor tone")],"12/8 swagger on two notes — behind the beat, always.")],
"Cemetery Gates|Pantera": [("Clean Intro","Clean","Randall RG100 (clean channel)",(3,5.5,5,6,5,3.5),"Dean ML","Neck humbucker",[("Chorus","chorus",[("Rate",3),("Depth",5)],"Glassy width")],"Clean arpeggios then the harmonic screams — whammy + harmonics at the outro.")],
"This Love|Pantera": [("Verse (Clean)","Clean","Randall RG100 (clean channel)",(3,5.5,5,6,5,3),"Dean ML","Neck humbucker",[("Chorus","chorus",[("Rate",3),("Depth",5)],"Cold clean sheen")],"Whisper verse, murder chorus — set both channels before you start.")],
"I'm Broken|Pantera": [("Main","High Gain","Randall Century 200",(8.5,6,3.5,7.5,6.5,0),"Dean ML","Bridge humbucker (L-500XL)",[],"The riff slinks — accent the slides between power chords.")],
"The Trooper|Iron Maiden": [("Main","High Gain","Marshall JMP",(7,5.5,5.5,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"Galloping triplets + twin harmonies — the Maiden formula at full charge.")],
"The Number of the Beast|Iron Maiden": [("Main","High Gain","Marshall JMP",(7,5.5,5.5,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"Verse riff gallops under spoken intro; solos trade Smith's melody vs Murray's legato.")],
"Run to the Hills|Iron Maiden": [("Main","High Gain","Marshall JMP",(7,5.5,5.5,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"The gallop IS the war drums — lock to the kick exactly.")],
"Hallowed Be Thy Name|Iron Maiden": [("Main","High Gain","Marshall JMP",(7,5.5,5.5,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"Bell-toll intro arpeggios build to the greatest closing solo section in metal.")],
"Aces High|Iron Maiden": [("Main","High Gain","Marshall JMP",(7,5.5,5.5,7,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"Fastest Maiden gallop — keep the wrist loose or crash.")],
"2 Minutes to Midnight|Iron Maiden": [("Main","Crunch","Marshall JMP",(6.5,5.5,5.5,6.5,5.5,0),"Gibson SG? Strat","Bridge humbucker",[],"Smith's swaggering riff — more rock'n'roll than gallop.")],
"Fear of the Dark|Iron Maiden": [("Main","High Gain","Marshall JCM800",(7,5.5,5.5,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"The quiet intro returns as a stadium chant — dynamics sell it.")],
"Wasted Years|Iron Maiden": [("Intro","Crunch","Marshall JMP",(6,5.5,6,6.5,5.5,1),"Jackson? Strat (modded)","Bridge humbucker",[("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"The cascading intro echo")],"The intro riff is one string + open-string pedal tones — let the delay do half the work.")],
"Breaking the Law|Judas Priest": [("Main","Crunch","Marshall JMP",(6.5,5.5,5.5,6.5,5.5,0),"Gibson Flying V? Hamer","Bridge humbucker",[],"Downpicked minor riff — punk energy, metal precision.")],
"Painkiller|Judas Priest": [("Main","High Gain","Marshall JCM800",(8.5,6,4.5,7,6.5,0),"Hamer GT? Flying V","Bridge humbucker",[("Boost","boost",[("Level",8)],"Front-end push for the leads")],"Screaming top-end — solos are whammy-abused chaos over double kick.")],
"Living After Midnight|Judas Priest": [("Main","Crunch","Marshall JMP",(6,5.5,5.5,6.5,5.5,0),"Gibson Flying V","Bridge humbucker",[],"Party-metal chords on the backbeat — simple, huge.")],
"Electric Eye|Judas Priest": [("Main","High Gain","Marshall JCM800",(7.5,5.5,5,7,6,0),"Hamer? Flying V","Bridge humbucker",[],"The intro melody line is the hook — twin guitars in unison then harmony.")],

# ---------- GRUNGE / 90s ALT ----------
"Come as You Are|Nirvana": [("Main","Clean","Fender Twin? Mesa Studio",(3,5.5,5,5.5,4.5,2.5),"Fender Jaguar? Mustang","Bridge humbucker",[("EHX Small Clone","chorus",[("Rate",3)],"Depth up — the watery riff sound"),("Boss DS-2","distortion",[("Dist",7.5),("Turbo",5),("Level",6)],"Chorus sections")],"Riff tuned down a whole step (D standard) — play it lazy, half-behind the beat.")],
"Lithium|Nirvana": [("Verse (Clean)","Clean","Mesa/Boogie Studio .22",(3,5.5,5,5.5,4.5,2.5),"Fender Jaguar","Bridge humbucker",[("Boss DS-2","distortion",[("Dist",8),("Level",6)],"Stomped for every chorus")],"Verse chords staccato and muted; chorus explodes — the quiet/loud blueprint.")],
"In Bloom|Nirvana": [("Main","High Gain","Mesa/Boogie Studio .22 + Crown PA",(8,6,4,6,5,0),"Fender Jaguar","Bridge humbucker",[("Boss DS-2","distortion",[("Dist",8),("Level",6)],"The wall")],"Nevermind rhythm tone: scooped wall of grind, chords slightly rushed.")],
"Heart-Shaped Box|Nirvana": [("Verse","Clean","Fender Twin Reverb",(3,5.5,5,5.5,4.5,3),"Fender Jaguar","Neck pickup",[("EHX Big Muff? DS-1","fuzz",[("Sustain",7),("Tone",4.5),("Volume",6)],"Chorus eruption")],"In Utero rawness — verse almost whispered, chorus a landslide.")],
"Breed|Nirvana": [("Main","High Gain","Mesa/Boogie Studio .22",(8.5,6,4,6,5,0),"Fender Jaguar","Bridge humbucker",[("Boss DS-2","distortion",[("Dist",8.5),("Level",6)],"Full assault")],"One-chord tremolo grind — endurance test for the right hand.")],
"About a Girl|Nirvana": [("Main","Clean","Fender Twin Reverb",(3.5,5.5,5.5,5.5,4.5,2.5),"Fender Jaguar","Neck pickup",[],"Beatles chords through a grunge filter — Em to G forever.")],
"Alive|Pearl Jam": [("Main","Overdrive","Marshall JCM800",(6,5.5,6,6,5,1.5),"Fender Stratocaster","Bridge humbucker",[],"The riff bounces between open A and harmonics; solo is one long crescendo of bends.")],
"Even Flow|Pearl Jam": [("Main","Overdrive","Marshall JCM800",(6,5.5,6,6,5,1.5),"Fender Stratocaster","Bridge humbucker",[("Vox Wah","wah",[],"McCready's solo — SRV school")],"E-A funk-rock groove; ghost strums between chords.")],
"Black|Pearl Jam": [("Main","Clean","Fender Twin Reverb",(3.5,5.5,5.5,5.5,4.5,3),"Fender Stratocaster","Neck single-coil",[],"E-A with hammered suspensions; the outro solo cries — bend slow.")],
"Jeremy|Pearl Jam": [("Main","Clean","Fender Twin Reverb",(3.5,6,5.5,5.5,4.5,3),"12-string bass? Guitar arr.","Neck pickup",[],"The hook is a 12-string bass on the record — arpeggiate A-major shapes with open strings.")],
"Yellow Ledbetter|Pearl Jam": [("Main","Clean","Fender Twin Reverb",(4,5.5,5.5,6,5,3.5),"Fender Stratocaster","Neck single-coil",[],"Hendrix-style thumb-over embellishments around E–B–A — it's all touch.")],
"Man in the Box|Alice in Chains": [("Main","Overdrive","Bogner-modded Marshall",(7,6,5.5,6,5.5,0),"G&L Rampage","Bridge humbucker",[("Talk Box","wah",[],"The vocal melody doubles through a talk box")],"Half-step down; the riff bends a quarter-tone — tune to the sludge.")],
"Would?|Alice in Chains": [("Main","Overdrive","Bogner-modded Marshall",(6.5,6,5.5,6,5.5,0),"G&L Rampage","Bridge humbucker",[],"Bass owns the verse; guitar enters like dread arriving.")],
"Rooster|Alice in Chains": [("Intro (Clean)","Clean","Fender Twin Reverb",(3,5.5,5,5.5,4.5,3),"G&L Rampage","Neck pickup",[("Chorus","chorus",[("Rate",3),("Depth",5)],"Haunted shimmer")],"Clean arpeggios float; the chorus lands like artillery.")],
"Them Bones|Alice in Chains": [("Main","High Gain","Bogner-modded Marshall",(7.5,6,5,6.5,5.5,0),"G&L Rampage","Bridge humbucker",[],"7/8 riff of pure anxiety — count it, then forget counting.")],
"Nutshell|Alice in Chains": [("Main","Clean","Fender Twin Reverb",(3.5,5.5,5.5,5.5,4.5,3),"Gibson Les Paul","Neck humbucker",[],"Unplugged-adjacent — the lead breaks speak grief; play at conversation volume.")],
"Black Hole Sun|Soundgarden": [("Verse","Clean","Fender Twin? Mesa",(3.5,5.5,5,5.5,4.5,3),"Gibson ES-335","Neck humbucker",[("Leslie / Rotary","chorus",[("Speed",3),("Depth",6)],"The seasick swirl"),("Big Muff","fuzz",[("Sustain",7),("Tone",4),("Volume",6)],"Chorus wall")],"Drop D. Verse chords float in rotary swirl; chorus crushes.")],
"Rusty Cage|Soundgarden": [("Main","Crunch","Mesa/Boogie? Marshall",(6.5,6,5.5,6.5,5.5,0),"Fender Telecaster","Bridge single-coil",[],"Drop D racing riff that downshifts into the sludge outro — two songs in one.")],
"Outshined|Soundgarden": [("Main","Crunch","Marshall JCM800",(6.5,6,5.5,6,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Drop D, 7/4 groove — heavy but swinging.")],
"Spoonman|Soundgarden": [("Main","Crunch","Mesa/Boogie Dual Rectifier",(6.5,6,5.5,6.5,5.5,0),"Fender Telecaster","Bridge single-coil",[],"C–G drop tuning riff in 7 — percussion is the co-lead.")],
"Plush|Stone Temple Pilots": None,
"Interstate Love Song|Stone Temple Pilots": [("Main","Crunch","Vox AC30 + Marshall",(5.5,5.5,6,6,5,1.5),"Gibson Les Paul","Bridge humbucker",[],"Open-position color chords — the prettiest grunge riff; don't overdrive it.")],
"Vasoline|Stone Temple Pilots": [("Main","Crunch","Marshall JCM800",(6.5,5.5,5.5,6,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Two-note riff — all rhythm, robotic until the chorus blooms.")],
"Cherub Rock|The Smashing Pumpkins": [("Main","Fuzz","Marshall JMP + Big Muff",(6,5.5,5.5,6,5,0),"Fender Stratocaster","Bridge single-coil",[("EHX Big Muff (Op-Amp)","fuzz",[("Sustain",7.5),("Tone",5),("Volume",6.5)],"The Siamese Dream wall — layered dozens of times")],"Drum-corps intro, then total saturation. Double-track everything.")],
"Today|The Smashing Pumpkins": [("Intro (Clean)","Clean","Fender Twin? Marshall clean",(3,5.5,5,6,5,2.5),"Fender Stratocaster","Neck single-coil",[("EHX Big Muff (Op-Amp)","fuzz",[("Sustain",7.5),("Tone",5),("Volume",6.5)],"Everything after the intro")],"The little bent intro motif, then the Muff swallows the world.")],
"Bullet with Butterfly Wings|The Smashing Pumpkins": [("Main","Fuzz","Marshall JMP",(6.5,5.5,5.5,6,5,0),"Fender Stratocaster","Bridge single-coil",[("EHX Big Muff","fuzz",[("Sustain",7.5),("Tone",5),("Volume",6.5)],"Chorus rage")],"Whisper verse over bass, scream chorus — the Muff is the anger switch.")],
"Zero|The Smashing Pumpkins": [("Main","Fuzz","Marshall JMP",(6.5,5.5,5.5,6.5,5,0),"Fender Stratocaster","Bridge single-coil",[("EHX Big Muff","fuzz",[("Sustain",8),("Tone",5.5),("Volume",6.5)],"Industrial-tight fuzz")],"Eb tuning; the riff is metallic and clipped — mute aggressively.")],
"1979|The Smashing Pumpkins": [("Main","Clean","Fender Twin Reverb",(3,5.5,5,5.5,4.5,2.5),"Fender Stratocaster","Neck single-coil",[("Chorus","chorus",[("Rate",3),("Depth",4)],"Hazy nostalgia filter")],"Loops and lazy strums — the guitar is a texture, not a riff.")],
"Everlong|Foo Fighters": None,
"My Hero|Foo Fighters": [("Main","Crunch","Mesa/Boogie Dual Rectifier",(6.5,6,5.5,6,5.5,0),"Gibson Trini Lopez","Bridge humbucker",[],"Drop D; the verse is one chord hammered like a heartbeat.")],
"The Pretender|Foo Fighters": [("Main","High Gain","Vox AC30 + Mesa",(7,6,5.5,6.5,5.5,0),"Gibson DG-335","Bridge humbucker",[],"Quiet menace verse, full-band detonation — practice the transition.")],
"Monkey Wrench|Foo Fighters": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(7.5,6,5,6.5,5.5,0),"Gibson Explorer","Bridge humbucker",[],"Downstroke sixteenths — punk stamina with pop chords.")],
"Learn to Fly|Foo Fighters": [("Main","Crunch","Vox AC30",(5.5,5.5,5.5,6,5,1.5),"Gibson Trini Lopez","Bridge humbucker",[],"Jangly barre chords — brightness over gain.")],
"Times Like These|Foo Fighters": [("Main","Crunch","Vox AC30 + Mesa",(6,5.5,6,6.5,5,1),"Gibson DG-335","Bridge humbucker",[],"The D-A-B riff in 7/4 — count until it feels like 4.")],
"Best of You|Foo Fighters": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(7,6,5.5,6.5,5.5,0),"Gibson DG-335","Bridge humbucker",[],"Open chords strummed to splinters — rawness is the point.")],
"All My Life|Foo Fighters": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(7.5,6,5,6.5,5.5,0),"Gibson DG-335","Bridge humbucker",[],"Muted stabs on one string build to the drop — tension is the hook.")],
"Basket Case|Green Day": [("Main","High Gain","Marshall 1959 SLP (modded 'Pete')",(7.5,6,5.5,6.5,5.5,0),"Fernandes Stratocaster 'Blue'","Bridge humbucker",[],"The Dookie tone: one modded Plexi, no pedals, downstrokes forever.")],
"When I Come Around|Green Day": [("Main","Crunch","Marshall 1959 SLP (modded)",(6.5,6,5.5,6,5.5,0),"Fernandes 'Blue'","Bridge humbucker",[],"Mid-tempo strut — let the chords ring a hair longer than punk allows.")],
"American Idiot|Green Day": [("Main","High Gain","Marshall 1959 SLP (modded)",(7.5,6,5.5,6.5,5.5,0),"Gibson Les Paul Jr.","Bridge P-90",[],"Power chords as protest signs — all downstrokes, zero swing.")],
"Boulevard of Broken Dreams|Green Day": [("Main","Clean","Fender Twin? Marshall clean",(3.5,5.5,5.5,5.5,5,2.5),"Gibson Les Paul Jr.","Bridge P-90",[("Tremolo","chorus",[("Rate",4),("Depth",5)],"The lonely pulse on the verse riff")],"Fm arpeggio figure — tremolo does the crying.")],
"Holiday|Green Day": [("Main","High Gain","Marshall 1959 SLP (modded)",(7.5,6,5.5,6.5,5.5,0),"Gibson Les Paul Jr.","Bridge P-90",[],"March-tempo punk — the riff answers the vocal like a chant.")],
"Brain Stew|Green Day": [("Main","Crunch","Marshall 1959 SLP (modded)",(6.5,6,5.5,6,5.5,0),"Fernandes 'Blue'","Bridge humbucker",[],"Five descending chords, forever — space between them is the menace.")],
"Longview|Green Day": [("Verse (Clean)","Clean","Fender Twin Reverb",(3,5.5,5.5,5.5,4.5,2),"Fernandes 'Blue'","Bridge humbucker",[],"Bass carries the verse; guitar only detonates the chorus.")],
"Welcome to Paradise|Green Day": [("Main","High Gain","Marshall 1959 SLP (modded)",(7.5,6,5.5,6.5,5.5,0),"Fernandes 'Blue'","Bridge humbucker",[],"The breakdown's palm-muted build is the whole song's payoff.")],
"Self Esteem|The Offspring": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(7.5,6,5,6.5,5.5,0),"Ibanez? custom","Bridge humbucker",[],"Grunge-weight chords at punk tempo; the 'la la la' riff stays clean-ish.")],
"The Kids Aren't Alright|The Offspring": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(8,6,5,6.5,5.5,0),"Ibanez? custom","Bridge humbucker",[],"Sixteenth-note downstrokes at 100+ BPM — a forearm workout.")],
"All the Small Things|blink-182": [("Main","High Gain","Marshall JCM900 + Mesa",(7.5,6,5.5,6.5,5.5,0),"Fender Stratocaster (Tom Delonge)","Bridge humbucker",[],"Three chords, giant single humbucker — the simplest tone that ever ruled radio.")],
"Dammit|blink-182": [("Main","High Gain","Marshall JCM900",(7.5,6,5.5,6.5,5.5,0),"Fender Stratocaster (modded)","Bridge humbucker",[],"The riff is the melody — keep every note even at speed.")],
"Buddy Holly|Weezer": [("Main","High Gain","Mesa/Boogie Mark I reissue",(7.5,6,5.5,6,5.5,0),"Gibson Les Paul Special","Bridge P-90",[],"The 'wall of Ws': layered fuzzy crunch, chords always full voicings.")],
"Say It Ain't So|Weezer": [("Verse (Clean)","Clean","Fender Twin? Mesa clean",(3,5.5,5,5.5,4.5,3),"Gibson Les Paul Special","Bridge P-90",[],"Reggae-ish upstroke verse; the chorus stomp is sudden and total.")],
"Zombie|The Cranberries": [("Main","Fuzz","Fender Twin + Big Muff",(5,6,5,5.5,5,2),"Fender Stratocaster","Bridge humbucker",[("EHX Big Muff","fuzz",[("Sustain",7),("Tone",4.5),("Volume",6)],"The grief-wall on the chorus")],"Four chords, endless — dynamics come only from the fuzz switch.")],
"Creep|Radiohead": [("Main","Clean","Fender Twin? Vox",(3.5,5.5,5.5,6,5,2.5),"Fender Telecaster","Bridge single-coil",[("Marshall Shredmaster","distortion",[("Gain",7),("Contour",5),("Volume",6)],"The 'chunk-chunk' stabs before each chorus")],"Jonny's dead-note crunches are sabotage-as-hook.")],
"Paranoid Android|Radiohead": [("Heavy Section","High Gain","Fender? Vox AC30",(7.5,5.5,5.5,6.5,5,0),"Fender Telecaster Plus","Bridge humbucker",[("Marshall Shredmaster","distortion",[("Gain",7.5),("Contour",4.5),("Volume",6)],"The 7/8 freak-out")],"Three songs stitched together; the outro solo fights the time signature on purpose.")],
"Just|Radiohead": [("Main","High Gain","Vox AC30",(7,5.5,5.5,6.5,5,0),"Fender Telecaster Plus","Bridge humbucker",[("Marshall Shredmaster","distortion",[("Gain",7.5),("Contour",5),("Volume",6)],"Solo + chorus"),],"Chord shapes climbing chromatically — the solo is a whammy-bar seizure.")],
"Karma Police|Radiohead": [("Main","Clean","Vox AC30",(3,5.5,5.5,5.5,4.5,2.5),"Fender Telecaster","Neck single-coil",[],"Piano leads; guitar shadows the chords — restraint throughout.")],
"My Iron Lung|Radiohead": [("Main","High Gain","Vox AC30",(7,5.5,5.5,6.5,5,0),"Fender Telecaster Plus","Bridge humbucker",[("Marshall Shredmaster","distortion",[("Gain",7.5),("Contour",5),("Volume",6)],"The mid-song ambush")],"Gentle arpeggios lulling you before the Shredmaster violence.")],
"Street Spirit (Fade Out)|Radiohead": [("Main","Clean","Vox AC30",(2.5,5.5,5.5,6,5,3),"Fender Telecaster","Neck single-coil",[],"Am arpeggio perpetual motion — even eighths, zero rubato.")],
"No Surprises|Radiohead": [("Main","Clean","Vox AC30",(2.5,5.5,5,6.5,5,3),"Fender Telecaster","Neck single-coil",[],"Music-box figure with capo high — play it like a lullaby.")],
"Wonderwall|Oasis": [("Electric Layer","Clean","Vox AC30? Marshall clean",(3.5,5.5,5.5,6,5,2.5),"Epiphone Riviera","Bridge humbucker",[],"Capo 2. The electric just halos the acoustic — sustain single notes under the chorus.")],
"Don't Look Back in Anger|Oasis": [("Main","Crunch","Marshall? Vox blend",(5.5,5.5,6,6,5,2),"Gibson Les Paul","Bridge humbucker",[],"Piano intro, then wall-of-guitars C major — solo is pentatonic singalong.")],
"Live Forever|Oasis": [("Main","Crunch","Marshall JCM900? Vox",(5.5,5.5,6,6,5,2),"Epiphone Les Paul","Bridge humbucker",[],"G-D-Am7-C loop; the solo repeats the vocal melody an octave up.")],
"Champagne Supernova|Oasis": [("Main","Clean","Vox AC30",(3.5,5.5,5.5,6,5,3),"Epiphone Riviera","Neck humbucker",[],"Aadd9 drones through everything — let open strings ring across all changes.")],
"Supersonic|Oasis": [("Main","Crunch","Marshall JCM900",(6,5.5,6,6,5,1.5),"Epiphone Les Paul","Bridge humbucker",[],"F#m strut; the lead fills are lazy on purpose.")],
"Cigarettes & Alcohol|Oasis": [("Main","Crunch","Marshall JCM900",(6,5.5,6,6.5,5,1),"Epiphone Les Paul","Bridge humbucker",[],"T. Rex riff worn proudly — swagger over accuracy.")],
"Do I Wanna Know?|Arctic Monkeys": [("Main","Fuzz","Vox AC30 + Fender",(5.5,6,5.5,5.5,5,1.5),"Fender Jazzmaster? LP","Bridge humbucker",[("Fuzz","fuzz",[("Sustain",6),("Tone",4.5),("Volume",6)],"Thick, dark riff fuzz")],"The riff is half-time and hypnotic — play behind the beat, never rush.")],
"R U Mine?|Arctic Monkeys": [("Main","Fuzz","Vox AC30 + Orange",(6,6,5.5,5.5,5,1),"Gibson Les Paul? SG","Bridge humbucker",[("Fuzz","fuzz",[("Sustain",6.5),("Tone",4.5),("Volume",6)],"Dark garage fuzz")],"Falsetto hook over a riff that pivots between octaves.")],
"505|Arctic Monkeys": [("Main","Clean","Fender Twin? Vox",(3,5.5,5.5,5.5,5,3),"Fender Stratocaster","Neck single-coil",[("Tremolo","chorus",[("Rate",3.5),("Depth",4)],"The organ-like pulse")],"Two chords building forever — the outro lets everything overdrive at once.")],
"I Bet You Look Good on the Dancefloor|Arctic Monkeys": [("Main","Crunch","Vox AC30",(6,5.5,6,6.5,5,1),"Fender Stratocaster","Bridge single-coil",[],"Sixteenth-note strumming at sprint tempo — all wrist.")],
"Seven Nation Army|The White Stripes": None,
"Fell in Love with a Girl|The White Stripes": [("Main","Fuzz","Silvertone 1485",(6.5,5.5,5.5,6,5,0),"Airline JB Hutto","Bridge pickup",[("Big Muff","fuzz",[("Sustain",7),("Tone",5),("Volume",6)],"Red-raw garage fuzz")],"90 seconds, zero fat — chords slashed, never strummed.")],
"The Hardest Button to Button|The White Stripes": [("Main","Fuzz","Silvertone 1485",(6,6,5.5,5.5,5,0),"Airline JB Hutto","Bridge pickup",[("Big Muff","fuzz",[("Sustain",6.5),("Tone",4.5),("Volume",6)],"Round dark fuzz")],"One note against the kick drum — repetition as force.")],
"Icky Thump|The White Stripes": [("Main","Fuzz","Silvertone + Fender",(6.5,6,5.5,6,5,0),"Airline? Res-O-Glas","Bridge pickup",[("Big Muff","fuzz",[("Sustain",7),("Tone",5),("Volume",6.5)],"Main crunch"),("DigiTech Whammy","octave",[],"The seasick pitch-bend fills")],"Led Zeppelin filtered through a pawn shop — bend everything.")],
"Lonely Boy|The Black Keys": [("Main","Fuzz","Fender Quad Reverb",(6,6,5.5,5.5,5,1.5),"Gibson ES-330? Harmony","Bridge P-90",[("Fuzz","fuzz",[("Sustain",6.5),("Tone",4.5),("Volume",6)],"Greasy garage fuzz")],"The riff shuffles — swing the sixteenths like a boogie.")],
"Tighten Up|The Black Keys": [("Main","Fuzz","Fender Quad Reverb",(5.5,6,5.5,5.5,5,2),"Gibson ES-330","Bridge P-90",[("Fuzz","fuzz",[("Sustain",6),("Tone",4.5),("Volume",6)],"Warm vintage fuzz")],"Whistled hook, spare riff — space is the groove.")],
"Gold on the Ceiling|The Black Keys": [("Main","Fuzz","Fender Quad Reverb",(6,6,5.5,5.5,5,1.5),"Gibson ES-330","Bridge P-90",[("Fuzz","fuzz",[("Sustain",6.5),("Tone",4.5),("Volume",6)],"Glam-stomp fuzz")],"Boogie chords with an octave fuzz sheen — strut tempo.")],
"No One Knows|Queens of the Stone Age": [("Main","Fuzz","Ampeg VT-40? Marshall",(6.5,6,5.5,5.5,5,0),"Ovation Ultra GP","Bridge humbucker",[],"The QOTSA sound is amp+guitar, barely any pedals — robotic precision riffing, C standard tuning.")],
"Go with the Flow|Queens of the Stone Age": [("Main","Fuzz","Ampeg? Marshall",(6.5,6,5.5,5.5,5,0),"Ovation? Maton","Bridge humbucker",[],"Straight eighths like a piston engine — no swing whatsoever.")],
"Mr. Brightside|The Killers": [("Main","Crunch","Vox AC30",(5.5,5.5,6,6.5,5,1.5),"Fender Telecaster","Bridge single-coil",[("Delay","delay",[("Time",3),("Repeats",2.5),("Mix",3)],"The sparkling intro arpeggio")],"The intro riff never stops — it IS the song; keep it chiming above the band.")],
"Sex on Fire|Kings of Leon": [("Main","Crunch","Vox AC30? Fender",(5.5,5.5,6,6.5,5,2),"Gibson ES-325","Bridge humbucker",[("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"Halo on the high riff")],"High-fret octave riff floats over the drive — anthemic, not aggressive.")],
"Use Somebody|Kings of Leon": [("Main","Crunch","Vox AC30",(5.5,5.5,6,6,5,2.5),"Gibson ES-325","Bridge humbucker",[("Reverb","reverb",[("Mix",4)],"Stadium air")],"Chords washed in space — strum through, never mute.")],

# ---------- FUNK/RATM/RHCP ----------
"Bulls on Parade|Rage Against the Machine": [("Main","High Gain","Marshall JCM800 2205 (50W)",(7.5,5.5,6,6,5.5,0),"Custom 'Arm the Homeless'","Bridge humbucker",[("Dunlop Cry Baby","wah",[],"The 'wikka-wikka' solo — killswitch + wah scratching"),("DigiTech Whammy","octave",[],"Set to harmony for texture")],"Drop D. The riff is a fist; the solo is a turntable made of guitar.")],
"Guerrilla Radio|Rage Against the Machine": [("Main","High Gain","Marshall JCM800 2205",(7.5,5.5,6,6,5.5,0),"Custom 'Arm the Homeless'","Bridge humbucker",[("DigiTech Whammy","octave",[],"Solo: 2-octave-up setting, talk-box-like phrasing"),("Wah","wah",[],"Filter sweeps")],"Drop D stomp — the solo is played through the Whammy two octaves up.")],
"Bombtrack|Rage Against the Machine": [("Main","High Gain","Marshall JCM800 2205",(7.5,5.5,6,6,5.5,0),"Custom 'Arm the Homeless'","Bridge humbucker",[],"Riff walks down while the groove stays planted — lock with the bass.")],
"Testify|Rage Against the Machine": [("Main","High Gain","Marshall JCM800 2205",(7.5,5.5,6,6,5.5,0),"Custom 'Arm the Homeless'","Bridge humbucker",[("DigiTech Whammy","octave",[],"Intro siren sweeps")],"The intro noise is Whammy abuse; the riff is pure diesel.")],
"Californication|Red Hot Chili Peppers": [("Main","Clean","Marshall Major + Silver Jubilee",(3,5.5,5,5.5,4.5,2),"Fender Stratocaster","Neck single-coil",[],"Two-note broken chords — fingertips soft, let the bass write the harmony.")],
"Scar Tissue|Red Hot Chili Peppers": [("Main","Clean","Marshall Silver Jubilee",(3.5,5.5,5,6,4.5,2),"Fender Stratocaster","Neck single-coil",[],"The slide fills between chords are the vocal's shadow.")],
"Otherside|Red Hot Chili Peppers": [("Main","Clean","Marshall Silver Jubilee",(3.5,5.5,5,5.5,4.5,2.5),"Fender Stratocaster","Neck single-coil",[],"Am arpeggio verse; chorus chords brushed, not hit.")],
"Can't Stop|Red Hot Chili Peppers": [("Main","Clean","Marshall Silver Jubilee",(4,5.5,5,6,4.5,1.5),"Fender Stratocaster","Middle + bridge (position 2)",[],"Ghost-note sixteenths — the left hand mutes more than it frets.")],
"By the Way|Red Hot Chili Peppers": [("Chorus Riff","Crunch","Marshall Major",(6,5.5,5.5,6,5,1),"Fender Stratocaster","Bridge single-coil",[],"Verse is punk downstrokes; pre-chorus flips to funk — two right hands in one song.")],
"Give It Away|Red Hot Chili Peppers": [("Main","Crunch","Marshall JCM800",(5.5,5.5,5.5,6,5,1),"Fender Stratocaster","Bridge single-coil",[("Envelope Filter? Wah","wah",[],"Solo textures")],"A-string riff with rakes — all percussion, barely pitch.")],
"Snow (Hey Oh)|Red Hot Chili Peppers": [("Main","Clean","Marshall Silver Jubilee",(3,5.5,5,6,4.5,2),"Fender Stratocaster","Neck single-coil",[],"The fastest 'clean' riff in radio history — economy picking, feather touch.")],
"Dani California|Red Hot Chili Peppers": [("Solo","Lead","Marshall Silver Jubilee",(6.5,5.5,6,6,5,2),"Fender Stratocaster","Bridge single-coil",[("Big Muff","fuzz",[("Sustain",7),("Tone",4.5),("Volume",6)],"Hendrix-tribute outro solo")],"Verse funk minimal; the outro solo goes full Jimi — wide bends, fuzz singing.")],
"Cult of Personality|Living Colour": [("Main","High Gain","Marshall? Mesa hybrid",(7.5,5.5,6,6.5,5.5,0),"ESP? Hamburglar custom","Bridge humbucker",[("Wah","wah",[],"Solo screams")],"The riff bounces between E and G like a prizefighter — solo is chaos theory.")],

# ---------- MODERN / MUSE / ROYAL BLOOD ----------
"Plug In Baby|Muse": [("Main","Fuzz","Marshall + Diezel VH4",(7,5.5,6,6.5,5.5,0),"Manson DL-1","Bridge humbucker",[("ZVEX Fuzz Factory","fuzz",[("Gate",5),("Comp",4),("Drive",7),("Stab",6)],"Built into Bellamy's Manson — velcro-ripping fuzz")],"The riff is a baroque run through a broken synthesizer — precision inside chaos.")],
"Hysteria|Muse": [("Main","Fuzz","Marshall + VH4",(7,6,6,6,5.5,0),"Manson DL-1","Bridge humbucker",[("Fuzz Factory","fuzz",[("Drive",7),("Stab",6)],"On the stabs")],"Guitar answers the bass riff with octave stabs — leave the low end alone.")],
"Knights of Cydonia|Muse": [("Main","Fuzz","Marshall + VH4",(7,5.5,6,6.5,5.5,1.5),"Manson DL-1","Bridge humbucker",[("Fuzz Factory","fuzz",[("Drive",7),("Stab",6)],"Gallop fuzz"),("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"Spaghetti-western twang sections")],"Surf-metal gallop — morricone twang into fuzz apocalypse.")],
"Supermassive Black Hole|Muse": [("Main","Fuzz","Diezel VH4",(6.5,5.5,5.5,6,5.5,0),"Manson DL-1","Bridge humbucker",[("Fuzz Factory","fuzz",[("Drive",6.5),("Stab",5.5)],"Prince-meets-fuzz stabs")],"Falsetto funk — the riff is clipped, robotic, sexy.")],
"Stockholm Syndrome|Muse": [("Main","High Gain","Marshall + VH4",(7.5,5.5,6,6.5,5.5,0),"Manson DL-1","Bridge humbucker",[("Fuzz Factory","fuzz",[("Drive",7),("Stab",6)],"Chorus wall")],"Riff cascades down in sextuplets — Rachmaninoff with a fuzzbox.")],
"New Born|Muse": [("Main","High Gain","Marshall + VH4",(7.5,5.5,6,6.5,5.5,0),"Manson DL-1","Bridge humbucker",[("Fuzz Factory","fuzz",[("Drive",7),("Stab",6)],"Post-piano detonation")],"Piano arpeggio, then the riff arrives like a system crash.")],
"Out of the Black|Royal Blood": [("Main (Bass rig)","Fuzz","Ampeg + Marshall guitar amp split",(7,6.5,5,5.5,5,0),"Gretsch bass (played as guitar)","Split signal",[("Octave","octave",[],"Bass split into guitar registers — the 'how is that a bass' trick"),("Fuzz","fuzz",[("Sustain",7),("Tone",5),("Volume",6.5)],"The top layer snarl")],"It's a bass through pitch-split rigs — on guitar: drop tuning + octave-down pedal gets close.")],
"Figure It Out|Royal Blood": [("Main (Bass rig)","Fuzz","Ampeg + Marshall split",(7,6.5,5,5.5,5,0),"Gretsch bass","Split signal",[("Octave","octave",[],"Up-octave layer"),("Fuzz","fuzz",[("Sustain",7),("Tone",5),("Volume",6.5)],"Snarl")],"Riff swings — the groove matters more than the wall.")],
"Woman|Wolfmother": [("Main","Fuzz","Marshall Super Lead",(6.5,5.5,6,6.5,5.5,0),"Gibson SG","Bridge humbucker",[("Big Muff","fuzz",[("Sustain",7.5),("Tone",5),("Volume",6.5)],"Sabbath-revival fuzz")],"2000s doing 1971 — ride the riff like a wave.")],
"Highway Tune|Greta Van Fleet": [("Main","Crunch","Marshall Super Lead? AC30",(6,5.5,6.5,6.5,5.5,0),"Gibson SG","Bridge humbucker",[],"Zeppelin-school bends and stabs — attitude over complexity.")],

# ---------- NU/ALT METAL ----------
"Chop Suey!|System of a Down": [("Main","High Gain","Mesa/Boogie Triple Rectifier",(8.5,6.5,4,6.5,6,0),"Ibanez Iceman","Bridge humbucker",[],"Drop C. The riff flips between delicate picking and full detonation mid-bar.")],
"Toxicity|System of a Down": [("Main","High Gain","Mesa/Boogie Triple Rectifier",(8,6.5,4.5,6.5,6,0),"Ibanez Iceman","Bridge humbucker",[],"Drop C; verse harmonics ring like bells before the stomp.")],
"B.Y.O.B.|System of a Down": [("Main","High Gain","Mesa/Boogie Triple Rectifier",(8.5,6.5,4,7,6,0),"Ibanez Iceman","Bridge humbucker",[],"Thrash verse, disco chorus — two amps in one song if you can.")],
"Aerials|System of a Down": [("Main","High Gain","Mesa/Boogie Triple Rectifier",(7.5,6.5,5,6,6,1),"Ibanez Iceman","Bridge humbucker",[],"Drop C drone — the riff is a raga; sustain everything.")],
"Freak on a Leash|Korn": [("Main","High Gain","Mesa/Boogie Triple Rectifier",(8,7,3.5,6,6,0),"Ibanez K7 (7-string)","Bridge humbucker",[],"7-string in A — the verse 'scratching' is muted pick noise as percussion.")],
"Blind|Korn": [("Main","High Gain","Mesa/Boogie Rectifier",(8,7,3.5,6,6,0),"Ibanez Universe (7-string)","Bridge humbucker",[],"THE nu-metal moment — the riff drops after four clicks; make it land like a building.")],
"Duality|Slipknot": [("Main","High Gain","Rivera KR7? Mesa",(8.5,6.5,4,6.5,6,0),"Ibanez? Jackson (7/B tuning)","Bridge humbucker",[],"Drop B. Verse riff churns; chorus opens into melody — control the chaos.")],
"Before I Forget|Slipknot": [("Main","High Gain","Rivera? Mesa",(8.5,6.5,4,6.5,6,0),"Ibanez? Jackson","Bridge humbucker",[],"Drop B groove — the riff swings underneath the blast.")],
"Psychosocial|Slipknot": [("Main","High Gain","Rivera? Mesa",(8.5,6.5,4,7,6,0),"Ibanez? Jackson","Bridge humbucker",[],"Drop B; harmonized chorus leads over tremolo chug.")],
"My Own Summer (Shove It)|Deftones": [("Main","High Gain","Marshall JCM900",(7.5,6.5,4.5,6,5.5,0),"Fender? Ibanez (7-string)","Bridge humbucker",[],"The riff breathes — staccato stabs, then silence; the space is the menace.")],
"Change (In the House of Flies)|Deftones": [("Main","Overdrive","Marshall JCM900 + Fender",(6.5,6,5,5.5,5,2),"Fender? 7-string","Bridge humbucker",[("Chorus","chorus",[("Rate",3),("Depth",5)],"Underwater shimmer on the verse")],"Dreamy verse, crushing chorus — shoegaze wearing metal's jacket.")],
"In the End|Linkin Park": [("Main","High Gain","Mesa/Boogie Dual Rectifier + PRS",(8,6.5,4,6.5,6,0),"PRS Custom 24","Bridge humbucker",[],"Drop D; the riff supports the piano hook — precision chug, no fills.")],
"Numb|Linkin Park": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(8,6.5,4.5,6.5,6,0),"PRS Custom 24","Bridge humbucker",[],"Drop D wall behind the synth — chords sustained full bars.")],
"One Step Closer|Linkin Park": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(8.5,6.5,4,6.5,6,0),"Ibanez? PRS","Bridge humbucker",[],"Drop D; the intro harmonic squeals cut through — pinch + whammy dip.")],
"Faint|Linkin Park": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(8,6.5,4.5,6.5,6,0),"PRS Custom 24","Bridge humbucker",[],"Sprint tempo chug under strings — sixteenth palm mutes, iron wrist.")],
"Schism|Tool": [("Main","Overdrive","Diezel VH4 + Marshall",(6.5,6,5.5,6,5.5,0),"Gibson Les Paul Custom (silverburst)","Bridge humbucker",[],"Drop D. The riff counts in 6.5/8 — feel it as a conversation, not math.")],
"Sober|Tool": [("Main","Overdrive","Marshall + Mesa blend",(6.5,6,5.5,6,5.5,0),"Gibson Les Paul Custom","Bridge humbucker",[],"Drop D; the verse is bass territory — guitar stabs only where it hurts.")],
"Forty Six & 2|Tool": [("Main","Overdrive","Diezel VH4 + Marshall",(6.5,6,5.5,6,5.5,0),"Gibson Les Paul Custom","Bridge humbucker",[],"Drop D groove that coils and strikes — mute between phrases.")],
"The Pot|Tool": [("Main","Overdrive","Diezel VH4",(6.5,6,5.5,6.5,5.5,0),"Gibson Les Paul Custom","Bridge humbucker",[],"Drop D; falsetto intro then the riff drops an anvil.")],
"Bat Country|Avenged Sevenfold": [("Main","High Gain","Mesa? Bogner Uberschall",(8.5,6,4.5,7,6,0),"Schecter Synyster Custom","Bridge humbucker",[],"Drop D thrash-pop — harmonized solos with metronome precision.")],
"Afterlife|Avenged Sevenfold": [("Solo","Lead","Bogner Uberschall",(8.5,6,5,7,6,1),"Schecter Synyster Custom","Bridge humbucker",[],"Synyster's sweep-picked showcase — practice at half speed for a month.")],
"Hail to the King|Avenged Sevenfold": [("Main","High Gain","Bogner? Marshall",(7.5,6,5,6.5,6,0),"Schecter Synyster Custom","Bridge humbucker",[],"Drop D stomp — deliberate, royal, all downstrokes.")],
"Laid to Rest|Lamb of God": [("Main","High Gain","Mesa Mark IV",(8.5,6,4.5,7,6.5,0),"Jackson? ESP","Bridge humbucker",[],"Drop D; the intro riff spirals — every note picked, zero legato.")],
"Redneck|Lamb of God": [("Main","High Gain","Mesa Mark IV",(8.5,6,4.5,7,6.5,0),"Jackson? ESP","Bridge humbucker",[],"Groove-metal swagger — the riff swings like a bar fight.")],
"Blood and Thunder|Mastodon": [("Main","High Gain","Marshall JCM800 + Orange",(8,6.5,5,6.5,6,0),"Gibson? First Act custom","Bridge humbucker",[],"Drop D? standard-ish sludge — hammer-on riff like a harpoon volley.")],
"Flying Whales|Gojira": [("Main","High Gain","Mesa Dual Rectifier? EVH",(8.5,6.5,4.5,6.5,6.5,0),"Charvel San Dimas","Bridge humbucker",[],"Drop D; the pick-scrape whale calls, then the tectonic groove.")],
"Pull Me Under|Dream Theater": [("Main","High Gain","Mesa/Boogie Mark IV",(8,6,5,6.5,6,1),"Ernie Ball Music Man JP","Bridge humbucker",[("TC Chorus","chorus",[("Rate",2.5),("Depth",4)],"Widens the cleans"),("Delay","delay",[("Time",4),("Repeats",3),("Mix",3)],"Lead lines")],"E minor riff over odd-meter kicks — Petrucci picks EVERY note.")],
"Bring Me to Life|Evanescence": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(8,6.5,4.5,6.5,6,0),"Ibanez? PRS (drop D)","Bridge humbucker",[],"Drop D wall under piano — chords whole-bar, let the strings ring dark.")],
"Misery Business|Paramore": [("Main","High Gain","Marshall? Bogner",(7.5,6,5,6.5,5.5,0),"Fender Telecaster? Gibson","Bridge humbucker",[],"Drop D pop-punk with a metal right hand — the intro riff bounces.")],
"Du Hast|Rammstein": [("Main","High Gain","Mesa Dual Rectifier",(8.5,6.5,4,6.5,6.5,0),"ESP Eclipse","Bridge humbucker (active)",[],"Drop D; industrial chug — play like a machine, that's the aesthetic.")],
"Sonne|Rammstein": [("Main","High Gain","Mesa Dual Rectifier",(8.5,6.5,4,6.5,6.5,0),"ESP Eclipse","Bridge humbucker (active)",[],"Slow, ceremonial drop-D chords — the space between hits is the dread.")],

# ---------- BLUES / CLAPTON / SRV / KNOPFLER ----------
"Layla|Eric Clapton": [("Main Riff","Overdrive","Fender Champ (cranked)",(6,5.5,6,6.5,5,1),"Fender Stratocaster","Bridge single-coil",[],"The riff answered by Duane's slide an octave up — a tiny Champ cranked to death.")],
"Cocaine|Eric Clapton": [("Main","Crunch","Music Man HD-130",(5,5.5,6,6,5,1.5),"Fender Stratocaster","Middle + bridge (position 2)",[],"Lazy behind-the-beat riff — the space IS the groove.")],
"Wonderful Tonight|Eric Clapton": [("Main","Clean","Music Man HD-130",(3,5.5,5.5,5.5,4.5,3),"Fender Stratocaster","Neck single-coil",[],"The melody speaks — soft fingers, volume rolled to 7, every bend to pitch.")],
"Crossroads|Eric Clapton": None,  # already gold above via Cream key
"Pride and Joy|Stevie Ray Vaughan": [("Main","Overdrive","Fender Vibroverb + Dumble",(6,5.5,6,6,5,2),"Fender Stratocaster 'Number One'","Neck single-coil",[("Ibanez Tube Screamer TS808","overdrive",[("Drive",4.5),("Tone",5),("Level",7)],"The Texas push")],"Heavy strings (13s), tuned half-step down — shuffle with thumb bass notes.")],
"Texas Flood|Stevie Ray Vaughan": [("Slow Blues","Overdrive","Fender Vibroverb",(6,5.5,6,6,5,2.5),"Fender Stratocaster 'Number One'","Neck single-coil",[("TS808","overdrive",[("Drive",4.5),("Tone",5),("Level",7)],"Singing sustain")],"Half-step down; every phrase begins with a rake and ends with vibrato.")],
"Cold Shot|Stevie Ray Vaughan": [("Main","Clean","Fender Vibroverb",(4,5.5,5.5,6,5,2.5),"Fender Stratocaster","Middle single-coil",[],"The wobble is a Fender Vibratone rotary — chorus pedal approximates it.")],
"Couldn't Stand the Weather|Stevie Ray Vaughan": [("Main","Overdrive","Fender Vibroverb + Marshall",(6,5.5,6,6,5,2),"Fender Stratocaster","Neck single-coil",[("TS808","overdrive",[("Drive",4.5),("Level",7)],"Push")],"The funk intro is muted rakes — pick hard, mute harder.")],
"Little Wing|Stevie Ray Vaughan": [("Main","Overdrive","Fender Vibroverb + Dumble",(5.5,5.5,6,6,5,3),"Fender Stratocaster","Neck single-coil",[("TS808","overdrive",[("Drive",4),("Level",7)],"Sustain for the melody")],"Instrumental — Hendrix's chord melody stretched into ten minutes of testimony.")],
"The Thrill Is Gone|B.B. King": [("Lead","Clean","Fender Twin Reverb? Lab Series L5",(3.5,5.5,6,6,5,3),"Gibson ES-355 'Lucille'","Neck humbucker",[],"One note with the butterfly vibrato says more than a run — breathe between phrases.")],
"Still Got the Blues|Gary Moore": [("Lead","Lead","Marshall JTM45 reissue? Soldano",(7,5.5,6.5,6,5.5,2.5),"Gibson Les Paul 'Greeny'","Neck humbucker",[("Ibanez Tube Screamer","overdrive",[("Drive",5),("Level",7)],"Push into sustain"),("Delay","delay",[("Time",4),("Repeats",3),("Mix",3)],"Air around the melody")],"The out-of-phase 'Greeny' neck tone — melody with infinite sustain, vibrato from the wrist.")],
"Parisienne Walkways|Gary Moore": [("Lead","Lead","Marshall? Soldano",(7,5.5,6.5,6,5.5,2.5),"Gibson Les Paul","Neck humbucker",[("Tube Screamer","overdrive",[("Drive",5),("Level",7)],"Sustain"),("Delay","delay",[("Time",4),("Repeats",3),("Mix",3)],"Space")],"THE held note — feedback sustain for four bars; stand close to the amp.")],
"Money for Nothing|Dire Straits": [("Main","Crunch","Laney? Marshall + wah-as-filter",(6.5,5.5,6.5,5.5,5,1),"Gibson Les Paul","Bridge humbucker",[("Cry Baby Wah (half-cocked)","wah",[],"Parked mid-sweep — the honk IS the sound")],"The famous tone was a mic accident + parked wah. Fingerstyle, no pick.")],
"Brothers in Arms|Dire Straits": [("Lead","Clean","Fender Vibrolux? Soldano",(4,5.5,6,5.5,5,3.5),"Gibson Les Paul","Neck humbucker",[("Delay","delay",[("Time",4.5),("Repeats",3),("Mix",3.5)],"Long dusk echoes")],"Every note placed like a word in a eulogy — fingerstyle, volume swells.")],
"Romeo and Juliet|Dire Straits": [("Main","Clean","Fender Vibrolux",(3,5.5,5.5,6,5,3),"National Style O (resonator)","N/A",[],"Open-G resonator fingerpicking — on electric: neck pickup, capo 3, roll the tone back.")],
"Telegraph Road|Dire Straits": [("Build + Solo","Clean","Fender Vibrolux? Marshall",(4.5,5.5,6,6,5,3),"Fender Stratocaster","Neck single-coil",[("Delay","delay",[("Time",4),("Repeats",3),("Mix",3)],"Widescreen air")],"14 minutes from whisper to storm — the outro solo cashes every check the song wrote.")],
"Sultans of Swing|Dire Straits": None,
"Black Magic Woman|Santana": [("Lead","Overdrive","Mesa/Boogie Mark I",(6.5,5.5,6.5,5.5,5,2),"Gibson SG Special","Neck pickup",[],"The Santana sustain: Boogie's cascading gain + neck pickup + perfectly still fretting hand.")],
"Europa|Santana": [("Lead","Lead","Mesa/Boogie Mark I",(7,5.5,6.5,5.5,5,2.5),"Gibson SG? Yamaha SG",  "Neck humbucker",[],"Melody as prayer — swell into notes, hold until feedback blooms.")],
"Samba Pa Ti|Santana": [("Lead","Overdrive","Mesa/Boogie Mark I",(6,5.5,6.5,5.5,5,2.5),"Gibson SG Special","Neck pickup",[],"Slow samba — play the melody like a singer who's in no hurry.")],
"Smooth|Santana": [("Lead","Overdrive","Mesa/Boogie Mark I? PRS era",(6.5,5.5,6.5,5.5,5,2),"PRS Santana","Neck humbucker",[],"Latin phrasing over pop changes — end every phrase with vibrato, not silence.")],
"Gravity|John Mayer": [("Lead","Clean","Two-Rock? Dumble-style",(4,5.5,6,5.5,5,3),"Fender Stratocaster","Neck single-coil",[("Klon Centaur","overdrive",[("Gain",3),("Treble",5),("Output",6.5)],"Transparent push for the solo")],"The solo is four notes done perfectly — bend slow, land exact, vibrato like breathing.")],
"Slow Dancing in a Burning Room|John Mayer": [("Main","Clean","Two-Rock",(4,5.5,6,5.5,5,3),"Fender Stratocaster","Neck single-coil",[("Klon Centaur","overdrive",[("Gain",3),("Output",6.5)],"Solo lift")],"The intro double-stops slide between chords — thumb over the neck.")],
"Neon|John Mayer": [("Main","Clean","Two-Rock? Fender",(3.5,5.5,5.5,6,5,2.5),"Fender Stratocaster","Neck single-coil",[],"Percussive thumb-slap fingerstyle — the riff is a drum pattern with pitches.")],
"Sharp Dressed Man|ZZ Top": [("Main","Crunch","Marshall JMP? Legend",(6,5,6,6.5,5.5,0),"Gibson Les Paul 'Pearly Gates'","Bridge humbucker",[],"Boogie in C — pinch harmonics between phrases, always in the pocket.")],
"Gimme All Your Lovin'|ZZ Top": [("Main","Crunch","Marshall? Legend",(6,5,6,6.5,5.5,0),"Gibson Les Paul 'Pearly Gates'","Bridge humbucker",[],"80s ZZ: tighter, sequenced feel — but the bends still drawl.")],
"Tush|ZZ Top": [("Main","Crunch","Marshall Super Lead",(5.5,5,6,6.5,5.5,0),"Gibson Les Paul 'Pearly Gates'","Bridge humbucker",[],"12-bar in G — slide fills answer every line.")],
"Cheap Sunglasses|ZZ Top": [("Main","Crunch","Marshall Super Lead",(5.5,5.5,6,6,5.5,0),"Gibson Les Paul","Bridge humbucker",[],"Greasy minor-key strut; the riff slinks, never stomps.")],

# ---------- U2 / POLICE / POST-PUNK ----------
"Where the Streets Have No Name|U2": [("Main","Clean","Vox AC30",(3.5,5.5,5.5,6.5,5,2),"Fender Stratocaster","Bridge single-coil",[("Korg SDD-3000","delay",[("Time",4),("Repeats",4),("Mix",4.5)],"Dotted-eighth — THE Edge sound"),("Compressor","compressor",[("Sustain",5.5)],"Evens the shimmer")],"Dotted-eighth delay turns sixteenths into an orchestra — play less, hear more.")],
"With or Without You|U2": [("Main","Clean","Vox AC30",(3,5.5,5.5,6,5,2.5),"Fender Stratocaster","Neck single-coil",[("Delay","delay",[("Time",4),("Repeats",3.5),("Mix",4)],"Halo"),],"The Infinite Guitar sustain on the record — an EBow gets you there.")],
"Pride (In the Name of Love)|U2": [("Main","Crunch","Vox AC30",(5,5.5,5.5,6.5,5,2),"Fender Stratocaster","Bridge single-coil",[("Korg SDD-3000","delay",[("Time",4),("Repeats",4),("Mix",4.5)],"Dotted-eighth chime")],"Chiming arpeggios — accuracy with the delay is everything; practice with a metronome.")],
"Sunday Bloody Sunday|U2": [("Main","Clean","Vox AC30",(4,5.5,5.5,6.5,5,2),"Fender Stratocaster","Bridge single-coil",[("Delay","delay",[("Time",3),("Repeats",3),("Mix",3.5)],"Military snap")],"The riff is a drum cadence on strings — martial downstrokes.")],
"New Year's Day|U2": [("Main","Clean","Vox AC30",(3.5,5.5,5.5,6.5,5,2.5),"Fender Stratocaster","Bridge single-coil",[("Delay","delay",[("Time",4),("Repeats",3.5),("Mix",4)],"Ice-rink air")],"Piano and guitar trade the hook — your fills answer the keys.")],
"Mysterious Ways|U2": [("Main","Crunch","Vox AC30",(5.5,5.5,5.5,6,5,1.5),"Fender Stratocaster","Bridge single-coil",[("Wah","wah",[],"The funk filter — slow sweeps, not chops")],"Achtung-era groove — the wah breathes with the riff.")],
"One|U2": [("Main","Clean","Vox AC30",(3.5,5.5,5.5,6,5,3),"Fender Stratocaster","Neck single-coil",[("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"Soft bloom")],"Arpeggios that never resolve — restraint carries the grief.")],
"Every Breath You Take|The Police": [("Main","Clean","Roland JC-120",(2.5,5.5,5,6.5,5,2),"Fender Telecaster","Bridge single-coil",[("Compressor","compressor",[("Sustain",6),("Attack",5)],"Even, piano-like attack"),("Chorus","chorus",[("Rate",3),("Depth",4.5)],"JC-120 stereo sheen")],"Add9 arpeggios with pinky stretches — every note equal volume, like a music box.")],
"Message in a Bottle|The Police": [("Main","Crunch","Marshall? Roland JC-120",(5,5.5,5.5,6.5,5,1.5),"Fender Telecaster","Bridge single-coil",[("Chorus","chorus",[("Rate",3),("Depth",5)],"The shimmer"),("Compressor","compressor",[("Sustain",5.5)],"Evenness")],"Sus2 arpeggio stretch riff — fingers, not positions.")],
"Roxanne|The Police": [("Main","Clean","Fender Twin? JC-120",(3,5.5,5.5,6,5,2),"Fender Telecaster","Bridge single-coil",[],"Reggae upstrokes on the offbeat — mute instantly after each chop.")],
"Walking on the Moon|The Police": [("Main","Clean","Roland JC-120",(2.5,5.5,5,6,5,3),"Fender Telecaster","Neck single-coil",[("Chorus","chorus",[("Rate",3),("Depth",5.5)],"Zero-gravity wobble"),("Delay","delay",[("Time",4),("Repeats",3),("Mix",3.5)],"Moon-walk space")],"One chord stab per bar — the space does the walking.")],
"How Soon Is Now?|The Smiths": [("Main","Clean","Fender Twin x4 (tremolo)",(4,5.5,5,5.5,4.5,3),"Gibson ES-355","Bridge humbucker",[("Tremolo x2 (synced)","chorus",[("Rate",5),("Depth",7)],"The throbbing — multiple amps' tremolo in sync"),("Slide","eq",[],"The crying slide line in F#")],"Open F# tuning shimmer — the wobble is the riff; slide wails over the top.")],
"This Charming Man|The Smiths": [("Main","Clean","Fender Twin? Roland",(3,5.5,5.5,6.5,5,2),"Fender Telecaster","Bridge single-coil",[],"Marr's rolling arpeggio — capo 2, every note a bell; no drive, ever.")],
"There Is a Light That Never Goes Out|The Smiths": [("Main","Clean","Fender Twin",(3,5.5,5.5,6,5,2.5),"Fender Telecaster? Rickenbacker","Bridge pickup",[],"Strummed sixteenths under the string melody — jangle with melancholy.")],
"Just Like Heaven|The Cure": [("Main","Clean","Fender? Vox",(3.5,5.5,5,6,5,3),"Fender Jazzmaster","Bridge single-coil",[("Chorus","chorus",[("Rate",3),("Depth",5.5)],"The 80s halo"),("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"Air")],"The descending intro riff sparkles — chorus pedal is non-negotiable.")],
"A Forest|The Cure": [("Main","Clean","Vox? Fender",(3.5,5.5,5,5.5,5,3.5),"Fender Jazzmaster","Neck pickup",[("Flanger","flanger",[("Rate",2),("Range",5.5),("Color",5)],"The cold fog"),("Delay","delay",[("Time",4),("Repeats",4),("Mix",4)],"Endless woods")],"Two chords in the mist — atmosphere over event.")],
"Love Will Tear Us Apart|Joy Division": [("Main","Clean","Vox? Fender",(3.5,5.5,5,6,5,2.5),"Gibson SG? Fender","Bridge pickup",[],"The guitar doubles the synth hook then leaves — economy as aesthetic.")],
"Where Is My Mind?|Pixies": [("Main","Clean","Fender Twin? Marshall",(4,5.5,5.5,6,5,3),"Fender Telecaster? Jazzmaster","Bridge pickup",[],"The lead is two notes ringing over strums — the ghost 'ooh' does the rest.")],
"Debaser|Pixies": [("Main","Crunch","Marshall JCM800",(6,5.5,5.5,6.5,5,1),"Fender Jazzmaster? Les Paul","Bridge pickup",[],"Surf-punk downstrokes racing the bassline.")],
"Only Shallow|My Bloody Valentine": [("Main","Fuzz","Fender? Marshall + reverse reverb",(7,5.5,5,5.5,5,4),"Fender Jazzmaster","Bridge single-coil",[("Big Muff? fuzz","fuzz",[("Sustain",7.5),("Tone",4.5),("Volume",6.5)],"The smear"),("Reverse Reverb","reverb",[("Mix",6)],"Glide-bent chords sampled backwards — the 'glide guitar'")],"Strum while working the trem arm — pitch is a suggestion, not a rule.")],
"Epic|Faith No More": [("Main","High Gain","Marshall JCM800",(7.5,6,5,6.5,5.5,0),"Gibson? custom","Bridge humbucker",[],"Funk verse (mute everything), metal chorus (open everything).")],

# ---------- SATRIANI / VAI / INSTRUMENTAL ----------
"Surfing with the Alien|Joe Satriani": [("Lead","Lead","Marshall JVM? 100W + boost",(7.5,5.5,6,6.5,5.5,1.5),"Ibanez JS","Bridge humbucker",[("Wah","wah",[],"Filter color on phrases"),("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"Air")],"Legato lines that never stop moving — pick only when the phrase restarts.")],
"Always with Me, Always with You|Joe Satriani": [("Lead","Lead","Marshall? Rockman",(6.5,5.5,6,6,5.5,2),"Ibanez JS","Bridge humbucker",[("Chorus","chorus",[("Rate",3),("Depth",4.5)],"Ballad gloss"),("Delay","delay",[("Time",4),("Repeats",3),("Mix",3.5)],"Sings between notes")],"The melody is the song — tap the arpeggio section with metronome patience.")],
"For the Love of God|Steve Vai": [("Lead","Lead","Bogner Ecstasy? Marshall",(8,5.5,6,6.5,5.5,2),"Ibanez JEM 'Evo'","Bridge humbucker",[("Wah","wah",[],"Vocal color"),("Delay","delay",[("Time",4),("Repeats",3.5),("Mix",3.5)],"Cathedral air")],"Ten minutes of sustain and prayer — the trem arm is another finger.")],
"Far Beyond the Sun|Yngwie Malmsteen": [("Lead","Lead","Marshall Super Lead (50W)",(7.5,5.5,6,6.5,5.5,2),"Fender Stratocaster (scalloped)","Neck single-coil (DiMarzio)",[("DOD 250 Overdrive","boost",[("Gain",4),("Level",8)],"The front-end push")],"Harmonic minor at 200 BPM — picking-hand economy is the whole secret.")],

# ---------- TURKISH GOLD ----------
"Her Şeyi Yak|Duman": [("Main","Overdrive","Fender Twin + RAT",(6.5,5.5,5.5,6,5,2),"Fender Jaguar? Strat","Bridge pickup",[("ProCo RAT","distortion",[("Distortion",6.5),("Filter",5),("Volume",6)],"Seattle'dan İstanbul'a — grunge kırığı")],"Grunge dinamiği: sözde fısıltı, nakaratta patlama. Akorları bırak, çalsın.")],
"Senden Daha Güzel|Duman": [("Main","Crunch","Fender Twin? Marshall",(5.5,5.5,5.5,6,5,2),"Fender Stratocaster","Bridge pickup",[("RAT","distortion",[("Distortion",6),("Volume",6)],"Nakarat duvarı")],"Riff basit, gruv derin — sekizlikleri sürükleyerek çal.")],
"Bu Akşam|Duman": [("Main","Clean","Fender Twin Reverb",(3.5,5.5,5,5.5,4.5,3),"Fender Stratocaster","Neck pickup",[],"Arpej + hüzün; nakaratta hafif drive yeter.")],
"Köprüaltı|Duman": [("Main","Clean","Fender Twin Reverb",(3.5,5.5,5.5,5.5,4.5,3),"Fender Stratocaster","Neck pickup",[],"Sokak ağzıyla ballad — vurgular sözle birlikte nefes alır.")],
"Belki Alışman Lazım|Duman": [("Main","Crunch","Fender Twin + RAT",(5.5,5.5,5.5,6,5,2),"Fender Stratocaster","Bridge pickup",[("RAT","distortion",[("Distortion",6),("Volume",6)],"Kırık ton")],"Riff tekrarında küçük süslemeler — fazlası gürültü.")],
"Sil Baştan|Şebnem Ferah": [("Main","Overdrive","Mesa/Boogie Dual Rectifier",(6.5,6,5,6,5.5,1.5),"Ibanez? PRS","Bridge humbucker",[],"Balad gövdesi, rock zirvesi — solo bölümünde sustain'e yaslan.")],
"Bu Aşk Fazla Sana|Şebnem Ferah": [("Main","Crunch","Mesa/Boogie? Marshall",(6,5.5,5.5,6,5.5,1),"Ibanez","Bridge humbucker",[],"90'lar Türk rock tınısı: parlak crunch, net arpejler.")],
"Fırtına|Şebnem Ferah": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(7.5,6,4.5,6.5,6,0),"Ibanez? ESP","Bridge humbucker",[],"Metin Türkcan riffleri — sıkı palm mute, keskin geçişler.")],
"Mayın Tarlası|Şebnem Ferah": [("Main","High Gain","Mesa/Boogie Dual Rectifier",(7.5,6,4.5,6.5,6,0),"Ibanez? ESP","Bridge humbucker",[],"Drop havasında agresif riff — boşluklar da riffin parçası.")],
"Cambaz|Mor ve Ötesi": [("Main","Crunch","Marshall JCM900? Mesa",(6.5,5.5,5.5,6,5.5,0.5),"Fender? Gibson SG","Bridge humbucker",[],"Riff inatçı ve köşeli — alternatif rock'ın Türkçe marşı; downstroke ağırlıklı.")],
"Bir Derdim Var|Mor ve Ötesi": [("Main","Crunch","Marshall? Mesa",(6,5.5,5.5,6,5.5,1),"Gibson SG? Fender","Bridge humbucker",[],"Söz aralarında riff nefes alır — dinamiği şarkı söyler.")],
"Deli|Mor ve Ötesi": [("Main","Crunch","Marshall JCM900",(6.5,5.5,5.5,6.5,5.5,0.5),"Gibson SG","Bridge humbucker",[],"Kısa, sinirli vuruşlar — punk enerjisi, alternatif ton.")],
"Uyan|Mor ve Ötesi": [("Main","Crunch","Marshall? Mesa",(6,5.5,5.5,6,5.5,1),"Gibson SG","Bridge humbucker",[],"Kreşendo mimarisi: fısıltıyla başla, duvarla bitir.")],
"Dursun Zaman|maNga": [("Main","High Gain","Peavey 5150? Mesa",(8,6.5,4,6.5,6,0),"Ibanez (drop C)","Bridge humbucker",[],"Drop C; elektronik katmanların altında sıkı çift-kick chug.")],
"Bir Kadın Çizeceksin|maNga": [("Main","High Gain","Peavey 5150",(8,6.5,4,6.5,6,0),"Ibanez (drop C)","Bridge humbucker",[],"Anadolu ezgisi + nu-metal riff — melodiyi ezme, taşı.")],
"We Could Be the Same|maNga": [("Main","High Gain","Peavey 5150? Mesa",(7.5,6.5,4.5,6.5,6,0),"Ibanez (drop C)","Bridge humbucker",[],"Eurovision cilası: nakaratta akorları açık bırak.")],
"Cevapsız Sorular|maNga": [("Main","High Gain","Peavey 5150",(7.5,6.5,4.5,6.5,6,0),"Ibanez (drop C)","Bridge humbucker",[],"Verse'te sus, nakaratta bas — dinamik makas geniş.")],
"Bir|Pentagram": [("Main","High Gain","Marshall JCM800? Mesa",(8,6,4.5,7,6,0),"ESP? Jackson","Bridge humbucker",[],"Anadolu makamıyla thrash — riff aksanları zurna gibi konuşur.")],
"Gündüz Gece|Pentagram": [("Main","Clean","Fender Twin? Mesa clean",(3,5.5,5.5,5.5,5,3),"ESP? Jackson","Neck humbucker",[],"Baladın yükü temiz arpejlerde — nakarat gain'i şarkının zirvesi.")],
"Şeytan Bunun Neresinde|Pentagram": [("Main","High Gain","Marshall? Mesa",(8,6,4.5,7,6,0),"ESP? Jackson","Bridge humbucker",[],"Galop ritmi — Maiden okulu, Anadolu aksanı.")],
"Anatolia|Pentagram": [("Main","High Gain","Marshall? Mesa",(8,6,4.5,7,6,0),"ESP? Jackson","Bridge humbucker",[],"Bağlama tavrı elektrikte — süslemeleri hammer-on'la söylet.")],
"Cemalim|Erkin Koray": [("Main","Fuzz","Vox? Selmer (cranked)",(6,5.5,6,6,5,1.5),"Custom elektro (bağlama tavırlı)","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",7.5),("Volume",6.5)],"Anadolu psych'in kalbi")],"Mikrotonal süslemeler — perde arası çeyrek ses bükmeler riffin ruhu.")],
"Estarabim|Erkin Koray": [("Main","Fuzz","Vox AC30 (cranked)",(6,5.5,6,6,5,1.5),"Fender? custom","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",7),("Volume",6.5)],"Şarkının imzası")],"Riff dansçı — fuzz'a rağmen artikülasyon kaybolmasın.")],
"Şaşkın|Erkin Koray": [("Main","Fuzz","Vox? Fender",(5.5,5.5,6,6,5,2),"Custom elektro","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",7),("Volume",6)],"70'ler İstanbul tınısı")],"Halk ezgisi + fuzz — melodiyi tane tane söylet.")],
"Fesuphanallah|Erkin Koray": [("Main","Fuzz","Vox? Fender",(5.5,5.5,6,6,5,2),"Custom elektro","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",7),("Volume",6)],"Psych grunge atası")],"Riff ağır çekim baş sallatır — aceleye getirme.")],
"Dağlar Dağlar|Barış Manço": [("Main","Clean","Fender Twin? Vox",(3,5.5,5.5,5.5,4.5,3.5),"Fender? Gibson","Neck pickup",[("Tremolo","chorus",[("Rate",3.5),("Depth",4.5)],"Dönem tınısı")],"Ağıt gibi — melodi vokalin gölgesinde yürür.")],
"Gülpembe|Barış Manço": [("Main","Clean","Fender Twin Reverb",(3,5.5,5.5,6,4.5,3.5),"Fender Stratocaster","Neck pickup",[("Chorus","chorus",[("Rate",3),("Depth",4.5)],"80'ler yumuşaklığı")],"Kurtalan Ekspres inceliği: az nota, çok duygu.")],
"Nick the Chopper|Barış Manço": [("Main","Fuzz","Orange? Vox (cranked)",(6,5.5,6,6,5,1.5),"Gibson SG? custom","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",7),("Volume",6.5)],"Anadolu psych funk")],"Funk gruvu + fuzz riff — sıkı, kesik vuruşlar.")],
"Tamirci Çırağı|Cem Karaca": [("Main","Crunch","Orange? Marshall (dönem)",(5.5,5.5,6,6,5,1.5),"Gibson SG? custom","Bridge pickup",[],"Anadolu rock klasiği — riff işçi türküsü gibi dürüst; süsleme az, vurgu tam.")],
"Namus Belası|Cem Karaca": [("Main","Crunch","Orange OR120",(5.5,5.5,6,6,5,1.5),"Gibson SG","Bridge pickup",[],"Dertli riff — bendleri konuşur gibi çek.")],
"Ay Karanlık|Cem Karaca": [("Main","Crunch","Orange? Vox",(5,5.5,6,5.5,5,2),"Gibson SG? custom","Neck pickup",[],"Karanlık balad — arpejlerde sözün acısı var.")],
"Ölüyorum|Hayko Cepkin": [("Main","High Gain","Mesa? ENGL",(8,6.5,4.5,6.5,6,0),"ESP? Ibanez (drop)","Bridge humbucker",[],"Scream'le riff aynı nefeste — drop tuning, sıkı gate.")],
"Sakin Olmam Lazım|Hayko Cepkin": [("Main","High Gain","Mesa? ENGL",(8,6.5,4.5,6.5,6,0),"ESP? Ibanez","Bridge humbucker",[],"İroni riffte: 'sakin' değil — patlamalar ani ve keskin.")],
"Papatya|Teoman": [("Main","Clean","Fender Twin? Vox",(3.5,5.5,5.5,5.5,4.5,3),"Fender Telecaster","Neck pickup",[],"Şehirli hüzün: arpej + boşluk; vokale alan bırak.")],
"İstanbul'da Sonbahar|Teoman": [("Main","Clean","Fender Twin Reverb",(3,5.5,5.5,5.5,4.5,3.5),"Fender Telecaster","Neck pickup",[("Reverb","reverb",[("Mix",4)],"Vapur sisi")],"Az nota, çok sis — melodi yürüyüş temposunda.")],
"Serseri|Teoman": [("Main","Crunch","Vox AC30",(5,5.5,5.5,6,5,2),"Fender Telecaster","Bridge pickup",[],"Rock'n roll tavrı — riff yalpalayarak yürür.")],
"Ben Böyleyim|Athena": [("Main","Crunch","Marshall JCM900",(6.5,5.5,5.5,6.5,5.5,0.5),"Fender? Ibanez","Bridge humbucker",[],"Ska-punk enerjisi: upstroke'lar keskin, nakarat tam gaz.")],
"Her Şey Yolunda|Athena": [("Main","Crunch","Marshall JCM900",(6.5,5.5,5.5,6.5,5.5,0.5),"Fender? Ibanez","Bridge humbucker",[],"Kesik ska vuruşları + punk nakarat — sağ el disiplini.")],
"Afili Yalnızlık|Emre Aydın": [("Main","Clean","Fender Twin? Vox",(3.5,5.5,5.5,5.5,5,3),"Fender? PRS","Neck pickup",[("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"Melankoli halkası")],"Arpej motifi şarkının kimliği — temiz ve tekrarcı.")],
"Yaz Gazeteci Yaz|Selda Bağcan": [("Main","Fuzz","Vox? dönem amfisi",(5.5,5.5,6,5.5,5,1.5),"Elektro bağlama? gitar","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",7),("Volume",6)],"Anadolu psych-protest tınısı")],"Protest türkünün elektrikli öfkesi — riff slogan gibi.")],
"Nerdesin|Bulutsuzluk Özlemi": [("Main","Crunch","Marshall? Roland",(5.5,5.5,5.5,6,5,1.5),"Fender Stratocaster","Bridge pickup",[],"80'ler Anadolu rock: net arpej, dürüst crunch.")],
"Sözlerimi Geri Alamam|Bulutsuzluk Özlemi": [("Main","Crunch","Marshall JCM800",(5.5,5.5,5.5,6,5,1.5),"Fender Stratocaster","Bridge pickup",[],"Riff inat gibi — aynı cümle, artan yoğunluk.")],
"Ele Güne Karşı|MFÖ": [("Main","Clean","Roland JC-120",(3,5.5,5,6,5,2.5),"Fender Stratocaster","Middle + neck",[("Chorus","chorus",[("Rate",3),("Depth",5)],"80'ler cilası")],"Funk-pop dokunuşları — akorlar kesik ve zarif.")],
"Goca Dünya|Altın Gün": [("Main","Fuzz","Fender? Vox (dönem repro)",(5.5,5.5,6,5.5,5,2),"Elektro bağlama + gitar","Bridge pickup",[("Vintage Fuzz","fuzz",[("Fuzz",6.5),("Volume",6)],"Retro psych"),("Phaser","phaser",[("Speed",3.5)],"70'ler döngüsü")],"Anadolu psych'in modern hali — gruv disko, tını 1974.")],
"Beni Bırakma|Feridun Düzağaç": [("Main","Clean","Fender Twin? Vox",(3.5,5.5,5.5,5.5,5,3),"Fender Stratocaster","Neck pickup",[("Delay","delay",[("Time",3.5),("Repeats",3),("Mix",3)],"FD melankolisi")],"Arpejler yağmur gibi — nakaratta hafif kırık yeter.")],
"Orada Ortada|Adamlar": [("Main","Crunch","Vox AC30? Fender",(5.5,5.5,5.5,6,5,2),"Fender Jazzmaster? Tele","Bridge pickup",[],"İndie tavır: gevşek bilek, kasıtlı dağınıklık.")],
"Aşk Nereden Nereye|Gripin": [("Main","Crunch","Marshall? Mesa",(6,5.5,5.5,6,5.5,1),"Ibanez? Fender","Bridge humbucker",[],"Pop-rock nakarat makinesi — köprüde dinamiği düşür, finalde patlat.")],
}


def to_tone(sid, idx, t):
    name, character, amp, s, guitar, pickup, pedals, notes = t
    g, b, m, tr, p, r = [float(x) for x in s]
    return {
        "id": f"{sid}-g{idx}", "name": name, "amp": amp.strip(), "character": character,
        "settings": {"gain": g, "bass": b, "mid": m, "treble": tr, "presence": p, "reverb": r},
        "guitar": guitar.strip(), "pickup": pickup.strip(),
        "pedals": [{
            "name": pn, "type": pt,
            "controls": [{"name": cn, "value": float(cv)} for cn, cv in pc],
            "note": pnote,
        } for (pn, pt, pc, pnote) in pedals],
        "notes": notes,
    }


def main():
    path = sys.argv[1]
    with open(path, encoding="utf-8") as f:
        songs = json.load(f)

    index = {}
    for song in songs:
        index[norm(song["title"]) + "|" + norm(song["artist"])] = song

    applied, missing = 0, []
    for key, tones in G.items():
        if tones is None:
            continue
        title, artist = key.split("|")
        k = norm(title) + "|" + norm(artist)
        song = index.get(k)
        if song is None:
            missing.append(key)
            continue
        song["tones"] = [to_tone(song["id"], i, t) for i, t in enumerate(tones)]
        applied += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(songs, f, ensure_ascii=False)
    print(f"gold tones applied to {applied} songs")
    if missing:
        print(f"NOT FOUND ({len(missing)}): {missing}")


if __name__ == "__main__":
    main()
